//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Tstdll32.rc
//
#define IDM_CPUID                       40001
#define IDM_EXIT                        40002
#define IDM_CPUID2                      40003
#define IDM_FEATUREFLAGS                40004
#define IDM_CPUSPEED                    40005
#define IDM_READ                        40006
#define IDM_GETDLLVERSION               40010
#define IDM_CMOSSPEED                   40011
#define IDM_BSFSPEED                    40012

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40013
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
