if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(NewAlbum==null)var NewAlbum={};
NewAlbum._path='/dwr';
NewAlbum.updateAlbumAccessCount=function(p0,callback){
dwr.engine._execute(NewAlbum._path,'NewAlbum','updateAlbumAccessCount',p0,callback);
}
NewAlbum.getNewAlbum=function(p0,callback){
dwr.engine._execute(NewAlbum._path,'NewAlbum','getNewAlbum',p0,callback);
}
NewAlbum.deleteNewAlbum=function(p0,callback){
dwr.engine._execute(NewAlbum._path,'NewAlbum','deleteNewAlbum',p0,callback);
}
NewAlbum.isFriend=function(p0,callback){
dwr.engine._execute(NewAlbum._path,'NewAlbum','isFriend',p0,callback);
}
NewAlbum.getAlbumAccessCount=function(p0,callback){
dwr.engine._execute(NewAlbum._path,'NewAlbum','getAlbumAccessCount',p0,callback);
}
NewAlbum.addAlbumFeedback=function(p0,p1,callback){
dwr.engine._execute(NewAlbum._path,'NewAlbum','addAlbumFeedback',p0,p1,callback);
}
NewAlbum.needUpdateModifyTime=function(p0,callback){
dwr.engine._execute(NewAlbum._path,'NewAlbum','needUpdateModifyTime',p0,callback);
}
NewAlbum.monitorAlbumCommCreate=function(){
dwr.engine._execute(NewAlbum._path,'NewAlbum','monitorAlbumCommCreate');
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(NewPhoto==null)var NewPhoto={};
NewPhoto._path='/dwr';
NewPhoto.getNewPhotos=function(p0,callback){
dwr.engine._execute(NewPhoto._path,'NewPhoto','getNewPhotos',p0,callback);
}
NewPhoto.updatePhotoAccessCount=function(p0,p1,callback){
dwr.engine._execute(NewPhoto._path,'NewPhoto','updatePhotoAccessCount',p0,p1,callback);
}
NewPhoto.deleteNewPhotos=function(p0,callback){
dwr.engine._execute(NewPhoto._path,'NewPhoto','deleteNewPhotos',p0,callback);
}
NewPhoto.setProfile=function(p0,callback){
dwr.engine._execute(NewPhoto._path,'NewPhoto','setProfile',p0,false,callback);
}
NewPhoto.addOrDelTag=function(p0,p1,p2,p3,p4,p5,p6,p7,p8,callback){
dwr.engine._execute(NewPhoto._path,'NewPhoto','addOrDelTag',p0,p1,p2,p3,p4,p5,p6,p7,p8,false,callback);
}
NewPhoto.copyPhotos=function(p0,callback){
dwr.engine._execute(NewPhoto._path,'NewPhoto','copyPhotos',p0,callback);
}
NewPhoto.isFriend=function(p0,callback){
dwr.engine._execute(NewPhoto._path,'NewPhoto','isFriend',p0,callback);
}
NewPhoto.getPhotosAccessCount=function(p0,callback){
dwr.engine._execute(NewPhoto._path,'NewPhoto','getPhotosAccessCount',p0,callback);
}
NewPhoto.needUpdateModifyTime=function(p0){
dwr.engine._execute(NewPhoto._path,'NewPhoto','needUpdateModifyTime',p0);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(Photo163==null)var Photo163={};
Photo163._path='http://photo.163.com/photo/dwrcross/';
Photo163.getUserSpace=function(p0,p1,callback){
var t=dwr.engine._rpcType;
var v=!!p1?'/u/'+p1:'';
dwr.engine.setMethod(dwr.engine.ScriptTag);
dwr.engine._execute(Photo163._path+p0+v+'/dwr','UserSpaceBean','getUserSpace',p0,callback);
dwr.engine.setMethod(t);
}
Photo163.getAlbumData=function(p0,p1,id,password,key,modifyTime,callback){
var t=dwr.engine._rpcType;
var v=!!p1?'/u/'+p1:'';
dwr.engine.setMethod(dwr.engine.ScriptTag);
dwr.engine._execute(Photo163._path+p0+v+'/dwr','AlbumBean','getAlbumData',id,password,key,modifyTime,false,callback);
dwr.engine.setMethod(t);
}
Photo163.getAlbumData4PwdInSession=function(p0,p1,callback){
var t=dwr.engine._rpcType;
var v=!!p1?'/u/'+p1:'';
dwr.engine.setMethod(dwr.engine.ScriptTag);
dwr.engine._execute(Photo163._path+p0+v+'/dwr','AlbumBean','getAlbumData4PwdInSession',false,callback);
dwr.engine.setMethod(t);
}
Photo163.getUserSpaceWithSec=function(p0,p1,callback){
var t=dwr.engine._rpcType;
var v=!!p1?'/u/'+p1:'';
dwr.engine.setMethod(dwr.engine.ScriptTag);
dwr.engine._execute(Photo163._path+p0+v+'/dwr','UserSpaceBean','getUserSpaceWithSec',p0,callback);
dwr.engine.setMethod(t);
}
Photo163.getAlbumData4Fav=function(p0,p1,id,apUserName,callback){
var t=dwr.engine._rpcType;
var v=!!p1?'/u/'+p1:'';
dwr.engine.setMethod(dwr.engine.ScriptTag);
dwr.engine._execute(Photo163._path+p0+v+'/dwr','AlbumBean','getAlbumData4BlogFavo',id,apUserName,callback);
dwr.engine.setMethod(t);
}
Photo163.reloadAlbumData=function(p0,p1,albumId,callback){
var t=dwr.engine._rpcType;
var v=!!p1?'/u/'+p1:'';
dwr.engine.setMethod(dwr.engine.ScriptTag);
dwr.engine._execute(Photo163._path+p0+v+'/dwr','AlbumBean','getAlbumData',albumId,'','','',false,callback);
dwr.engine.setMethod(t);
}
Photo163.reloadCommentsInAlbum=function(p0,p1,albumId,userId,callback){
var t=dwr.engine._rpcType;
var v=!!p1?'/u/'+p1:'';
dwr.engine.setMethod(dwr.engine.ScriptTag);
dwr.engine._execute(Photo163._path+p0+v+'/dwr','AlbumBean','getCommentData',albumId,userId,callback);
dwr.engine.setMethod(t);
}
Photo163.reloadCommentsInPhoto=function(p0,p1,albumId,photoId,userId,callback){
var t=dwr.engine._rpcType;
var v=!!p1?'/u/'+p1:'';
dwr.engine.setMethod(dwr.engine.ScriptTag);
dwr.engine._execute(Photo163._path+p0+v+'/dwr','PhotoBean','getCommentData',albumId,photoId,userId,callback);
dwr.engine.setMethod(t);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(Photo==null)var Photo={};
Photo._path='/dwr'
Photo.getHostAllTags=function(callback){
dwr.engine._execute(Photo._path,'Photo','getHostAllTags',false,callback);
}
Photo.updatePhotoPrivacy=function(p0,p1,p2,callback){
dwr.engine._execute(Photo._path,'Photo','updatePhotoPrivacy',p0,p1,p2,false,callback);
}
Photo.getUAStyle=function(callback){
dwr.engine._execute(Photo._path,'Photo','getUAStyle',callback);
}
Photo.addPhotoNote=function(p0,p1,p2,callback){
dwr.engine._execute(Photo._path,'Photo','addPhotoNote',p0,p1,p2,callback);
}
Photo.deletePhotos=function(p0,callback){
dwr.engine._execute(Photo._path,'Photo','deletePhotos',p0,false,callback);
}
Photo.getAllPhotoNote=function(p0,callback){
dwr.engine._execute(Photo._path,'Photo','getAllPhotoNote',p0,callback);
}
Photo.getPhoto=function(p0,callback){
dwr.engine._execute(Photo._path,'Photo','getPhoto',p0,callback);
}
Photo.getPhotosInAlbum=function(p0,p1,p2,p3,callback){
dwr.engine._execute(Photo._path,'Photo','getPhotosInAlbum',p0,p1,p2,p3,false,callback);
}
Photo.getPhotosInAlbum4MailAlbum=function(p0,p1,p2,p3,callback){
dwr.engine._execute(Photo._path,'Photo','getPhotosInAlbum4MailAlbum',p0,p1,p2,p3,false,callback);
}
Photo.getPhContextInAlbum=function(p0,p1,p2,p3,p4,p5,callback){
dwr.engine._execute(Photo._path,'Photo','getPhContextInAlbum',p0,p1,p2,p3,p4,p5,false,callback);
}
Photo.getPhContextInUser=function(p0,p1,p2,p3,callback){
dwr.engine._execute(Photo._path,'Photo','getPhContextInUser',p0,p1,p2,p3,false,callback);
}
Photo.getPhContextInUserById=function(p0,p1,p2,p3,callback){
dwr.engine._execute(Photo._path,'Photo','getPhContextInUserById',p0,p1,p2,p3,false,callback);
}
Photo.updatePhoto=function(p0,p1,p2,callback){
dwr.engine._execute(Photo._path,'Photo','updatePhoto',p0,p1,p2,false,callback);
}
Photo.getPhotosInUser=function(p0,p1,callback){
dwr.engine._execute(Photo._path,'Photo','getPhotosInUser',p0,p1,false,callback);
}
Photo.getPhotosInUser2=function(p0,p1,p2,p3,callback){
dwr.engine._execute(Photo._path,'Photo','getPhotosInUser2',p0,p1,p2,p3,false,callback);
}
Photo.getPhotosInUser4MailAlbum=function(p0,p1,callback){
dwr.engine._execute(Photo._path,'Photo','getPhotosInUser4MailAlbum',p0,p1,false,callback);
}
Photo.getPhotosInUserByTime=function(p0,p1,p2,p3,callback){
dwr.engine._execute(Photo._path,'Photo','getPhotosInUserByTime',p0,p1,p2,p3,callback);
}
Photo.getPhotosInUserByDate=function(p0,p1,p2,callback){
dwr.engine._execute(Photo._path,'Photo','getPhotosInUserByDate',p0,p1,p2,false,callback);
}
Photo.removePhotoNote=function(p0,p1,callback){
dwr.engine._execute(Photo._path,'Photo','removePhotoNote',p0,p1,callback);
}
Photo.updatePhotoNote=function(p0,p1,p2,callback){
dwr.engine._execute(Photo._path,'Photo','updatePhotoNote',p0,p1,p2,callback);
}
Photo.rotatePhoto=function(p0,p1,p2,p3,callback){
dwr.engine._execute(Photo._path,'Photo','rotatePhoto',p0,p1,p2,p3,false,callback);
}
Photo.trimPhoto=function(p0,p1,p2,p3,p4,callback){
dwr.engine._execute(Photo._path,'Photo','trimPhoto',p0,p1,p2,p3,p4,false,callback);
}
Photo.addPh2Favo=function(p0,p1,callback){
dwr.engine._execute(Photo._path,'Photo','addPh2Favo',p0,p1,callback);
}
Photo.getPhoInFavo=function(p0,p1,p2,callback){
dwr.engine._execute(Photo._path,'Photo','getPhoInFavo',p0,p1,p2,callback);
}
Photo.cleanPhoInFavo=function(p0,callback){
dwr.engine._execute(Photo._path,'Photo','cleanPhoInFavo',p0,callback);
}
Photo.removePhoFavo=function(p0,p1,p2,callback){
dwr.engine._execute(Photo._path,'Photo','removePhoFavo',p0,p1,p2,callback);
}
Photo.setProfile=function(p0,callback){
dwr.engine._execute(Photo._path,'Photo','setProfile',p0,false,callback);
}
Photo.recountAlbumCountInPhoto=function(p0,callback){
dwr.engine._execute(Photo._path,'Photo','recountAlbumCountInPhoto',p0,callback);
}
Photo.pushPhoto2Top=function(p0,callback){
dwr.engine._execute(Photo._path,'Photo','pushPhoto2Top',p0,callback);
}
Photo.getExif=function(p0,p1,callback){
dwr.engine._execute(Photo._path,'Photo','getExif',p0,p1,callback);
}
Photo.copyPhotos=function(p0,callback){
dwr.engine._execute(Photo._path,'Photo','copyPhotos',p0,false,callback);
}
Photo.getPhotosByUserIdForZipai=function(p0,p1,callback){
dwr.engine._execute(Photo._path,'Photo','getPhotosByUserIdForZipai',p0,p1,callback);
}
Photo.getSelfCapPhotos=function(p0,p1,p2,callback){
dwr.engine._execute(Photo._path,'Photo','getSelfCapPhotos',p0,p1,p2,callback);
}
Photo.refreshMailAlbum=function(callback){
dwr.engine._execute(Photo._path,'Photo','refreshMailAlbum',callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(SubscriptionBean==null)var SubscriptionBean={};
SubscriptionBean._path='/dwr';
SubscriptionBean.setEmailProducer=function(p0,callback){
dwr.engine._execute(SubscriptionBean._path,'SubscriptionBean','setEmailProducer',p0,callback);
}
SubscriptionBean.subscribByEmail=function(p0,p1,p2,callback){
dwr.engine._execute(SubscriptionBean._path,'SubscriptionBean','subscribByEmail',p0,p1,p2,callback);
}
SubscriptionBean.subscribByRss=function(p0,callback){
dwr.engine._execute(SubscriptionBean._path,'SubscriptionBean','subscribByRss',p0,callback);
}
SubscriptionBean.getEmailLimit=function(callback){
dwr.engine._execute(SubscriptionBean._path,'SubscriptionBean','getEmailLimit',callback);
}
SubscriptionBean.ShareByEmail=function(p0,p1,callback){
dwr.engine._execute(SubscriptionBean._path,'SubscriptionBean','ShareByEmail',p0,p1,callback);
}
SubscriptionBean.vaildMail=function(p0,p1,callback){
dwr.engine._execute(SubscriptionBean._path,'SubscriptionBean','vaildMail',p0,p1,callback);
}
SubscriptionBean.getSubList=function(p0,p1,p2,callback){
dwr.engine._execute(SubscriptionBean._path,'SubscriptionBean','getSubList',p0,p1,p2,callback);
}
SubscriptionBean.deleteSubs=function(p0,p1,callback){
dwr.engine._execute(SubscriptionBean._path,'SubscriptionBean','deleteSubs',p0,p1,callback);
}
SubscriptionBean.updateSubFreqc=function(p0,p1,p2,callback){
dwr.engine._execute(SubscriptionBean._path,'SubscriptionBean','updateSubFreqc',p0,p1,p2,callback);
}
SubscriptionBean.getVisitorRssLists=function(callback){
dwr.engine._execute(SubscriptionBean._path,'SubscriptionBean','getVisitorRssLists',callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(FocusMeBean==null)var FocusMeBean={};
FocusMeBean._path='/dwr';
FocusMeBean.getList=function(p0,callback){
dwr.engine._execute(FocusMeBean._path,'FocusMeBean','getList',p0,callback);
}
FocusMeBean.collectBlog=function(p0,p1,callback){
dwr.engine._execute(FocusMeBean._path,'FocusMeBean','collectBlog',p0,p1,false,callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(SpaceCircleBean==null)var SpaceCircleBean={};
SpaceCircleBean._path='/dwr';
SpaceCircleBean.setSecurityContextService=function(p0,callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','setSecurityContextService',p0,callback);
}
SpaceCircleBean.setEncryptService=function(p0,callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','setEncryptService',p0,callback);
}
SpaceCircleBean.getSecurityContextService=function(callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','getSecurityContextService',callback);
}
SpaceCircleBean.setSpaceCircleService=function(p0,callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','setSpaceCircleService',p0,callback);
}
SpaceCircleBean.isBlogRecommended=function(p0,callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','isBlogRecommended',p0,callback);
}
SpaceCircleBean.getBlogCircles=function(p0,p1,callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','getBlogCircles',p0,p1,callback);
}
SpaceCircleBean.getRecommendedBlogs=function(p0,p1,callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','getRecommendedBlogs',p0,p1,callback);
}
SpaceCircleBean.setRemindService=function(p0,callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','setRemindService',p0,callback);
}
SpaceCircleBean.getCircleConfig=function(callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','getCircleConfig',callback);
}
SpaceCircleBean.setCircleConfig=function(p0,callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','setCircleConfig',p0,callback);
}
SpaceCircleBean.getSpaceCircleService=function(callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','getSpaceCircleService',callback);
}
SpaceCircleBean.getUserShowCircles=function(p0,callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','getUserShowCircles',p0,callback);
}
SpaceCircleBean.getCircle=function(p0,callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','getCircle',p0,callback);
}
SpaceCircleBean.getUserSuccessCircles=function(p0,callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','getUserSuccessCircles',p0,callback);
}
SpaceCircleBean.getCircleType1List=function(callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','getCircleType1List',callback);
}
SpaceCircleBean.createCircle=function(p0,p1,callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','createCircle',p0,p1,callback);
}
SpaceCircleBean.getCircleByName=function(p0,callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','getCircleByName',p0,callback);
}
SpaceCircleBean.getUserCircles=function(p0,callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','getUserCircles',p0,callback);
}
SpaceCircleBean.deleteCircleUser=function(p0,p1,callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','deleteCircleUser',p0,p1,callback);
}
SpaceCircleBean.sendInvitation=function(p0,p1,callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','sendInvitation',p0,p1,false,callback);
}
SpaceCircleBean.acceptCircleInvitation=function(p0,p1,callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','acceptCircleInvitation',p0,p1,callback);
}
SpaceCircleBean.getRecommendedUsers=function(p0,p1,callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','getRecommendedUsers',p0,p1,callback);
}
SpaceCircleBean.getUserAdminCircles=function(callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','getUserAdminCircles',callback);
}
SpaceCircleBean.addAlbumToCircles=function(p0,p1,callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','addAlbumToCircles',p0,p1,callback);
}
SpaceCircleBean.getCircleService=function(callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','getCircleService',callback);
}
SpaceCircleBean.setCircleService=function(p0,callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','setCircleService',p0,callback);
}
SpaceCircleBean.getCircleByUrlName=function(p0,callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','getCircleByUrlName',p0,callback);
}
SpaceCircleBean.getCircleType2List=function(p0,callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','getCircleType2List',p0,callback);
}
SpaceCircleBean.checkCircleUnique=function(p0,callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','checkCircleUnique',p0,callback);
}
SpaceCircleBean.checkCreateCirclePriv=function(callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','checkCreateCirclePriv',callback);
}
SpaceCircleBean.getCircleCardData=function(p0,p1,p2,callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','getCircleCardData',p0,p1,p2,callback);
}
SpaceCircleBean.getUserCirclesByIdentity=function(p0,callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','getUserCirclesByIdentity',p0,callback);
}
SpaceCircleBean.getUserCirclesWithLimit=function(p0,p1,p2,callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','getUserCirclesWithLimit',p0,p1,p2,callback);
}
SpaceCircleBean.getCircleInvitationService=function(callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','getCircleInvitationService',callback);
}
SpaceCircleBean.setCircleInvitationService=function(p0,callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','setCircleInvitationService',p0,callback);
}
SpaceCircleBean.getCirclePushInfo=function(p0,callback){
dwr.engine._execute(SpaceCircleBean._path,'SpaceCircleBean','getCirclePushInfo',p0,callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(CircleBean==null)var CircleBean={};
CircleBean._path='http://q.163.com/dwr';
CircleBean.deleteCircle=function(p0,p1,callback){
var t=dwr.engine._rpcType;
dwr.engine.setMethod(dwr.engine.ScriptTag);
dwr.engine._execute(CircleBean._path,'CircleBean','deleteCircle',p0,p1,callback);
dwr.engine.setMethod(t);
};
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(HomepageSetupBean==null)var HomepageSetupBean={};
HomepageSetupBean._path='/dwr';
HomepageSetupBean.getCurUserPageSetup=function(callback){
dwr.engine._execute(HomepageSetupBean._path,'HomepageSetupBean','getCurUserPageSetup',false,callback);
}
HomepageSetupBean.changeModuleLayout=function(p0,callback){
dwr.engine._execute(HomepageSetupBean._path,'HomepageSetupBean','changeModuleLayout',p0,false,callback);
}
HomepageSetupBean.getLayouts=function(callback){
dwr.engine._execute(HomepageSetupBean._path,'HomepageSetupBean','getLayouts',false,callback);
}
HomepageSetupBean.getModules=function(callback){
dwr.engine._execute(HomepageSetupBean._path,'HomepageSetupBean','getModules',false,callback);
}
HomepageSetupBean.savePageSetup=function(p0,callback){
dwr.engine._execute(HomepageSetupBean._path,'HomepageSetupBean','savePageSetup',p0,false,callback);
}
HomepageSetupBean.initNewUserSettings=function(p0,p1,callback){
dwr.engine._execute(HomepageSetupBean._path,'HomepageSetupBean','initNewUserSettings',p0,p1,callback);
}
HomepageSetupBean.updateUserThemeToFixed=function(p0,callback){
dwr.engine._execute(HomepageSetupBean._path,'HomepageSetupBean','updateUserThemeToFixed',p0,false,callback);
}
HomepageSetupBean.getUserDefineThemeId=function(callback){
dwr.engine._execute(HomepageSetupBean._path,'HomepageSetupBean','getUserDefineThemeId',callback);
}
HomepageSetupBean.copyUserTheme=function(p0,p1,callback){
dwr.engine._execute(HomepageSetupBean._path,'HomepageSetupBean','copyUserTheme',p0,p1,callback);
}
HomepageSetupBean.getFixedThemsByTag=function(p0,callback){
dwr.engine._execute(HomepageSetupBean._path,'HomepageSetupBean','getFixedThemsByTag',p0,callback);
}
HomepageSetupBean.getHotFixedThemes=function(p0,callback){
dwr.engine._execute(HomepageSetupBean._path,'HomepageSetupBean','getHotFixedThemes',p0,callback);
}
HomepageSetupBean.getNewFixedThemes=function(p0,callback){
dwr.engine._execute(HomepageSetupBean._path,'HomepageSetupBean','getNewFixedThemes',p0,callback);
}
HomepageSetupBean.getColLimit=function(p0,callback){
DWREngine._execute(HomepageSetupBean._path,'HomepageSetupBean','getColLimit',p0,callback);
}
HomepageSetupBean.updateUserThemeId=function(p0,callback){
DWREngine._execute(HomepageSetupBean._path,'HomepageSetupBean','updateUserThemeId',p0,callback);
}
HomepageSetupBean.canCopyThisThemeToUser=function(p0,p1,p2,p3,callback){
DWREngine._execute(HomepageSetupBean._path,'HomepageSetupBean','canCopyThisThemeToUser',p0,p1,p2,p3,callback);
}
HomepageSetupBean.useThisTheme=function(p0,p1,callback){
dwr.engine._execute(HomepageSetupBean._path,'HomepageSetupBean','useThisTheme',p0,p1,callback);
}
HomepageSetupBean.collectThisThemeToMyFavourite=function(p0,p1,callback){
dwr.engine._execute(HomepageSetupBean._path,'HomepageSetupBean','collectThisThemeToMyFavourite',p0,p1,callback);
}
HomepageSetupBean.addRichModule=function(callback){
dwr.engine._execute(HomepageSetupBean._path,'HomepageSetupBean','addRichModule',false,callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(ResourceListBean==null)var ResourceListBean={};
ResourceListBean._path='/dwr';
ResourceListBean.getHostAllTags=function(callback){
dwr.engine._execute(ResourceListBean._path,'ResourceListBean','getHostAllTags',false,callback);
}
ResourceListBean.addResourceList=function(p0,p1,callback){
dwr.engine._execute(ResourceListBean._path,'ResourceListBean','addResourceList',p0,p1,false,callback);
}
ResourceListBean.addResourceItem=function(p0,p1,callback){
dwr.engine._execute(ResourceListBean._path,'ResourceListBean','addResourceItem',p0,p1,false,callback);
}
ResourceListBean.getResourceLists=function(p0,callback){
dwr.engine._execute(ResourceListBean._path,'ResourceListBean','getResourceLists',p0,false,callback);
}
ResourceListBean.getResourceList=function(p0,callback){
dwr.engine._execute(ResourceListBean._path,'ResourceListBean','getResourceList',p0,callback);
}
ResourceListBean.updateResourceList=function(p0,p1,p2,p3,callback){
dwr.engine._execute(ResourceListBean._path,'ResourceListBean','updateResourceList',p0,p1,p2,p3,false,callback);
}
ResourceListBean.deleteResourceList=function(p0,callback){
dwr.engine._execute(ResourceListBean._path,'ResourceListBean','deleteResourceList',p0,false,callback);
}
ResourceListBean.updateResourceListStyle=function(p0,p1,callback){
dwr.engine._execute(ResourceListBean._path,'ResourceListBean','updateResourceListStyle',p0,p1,callback);
}
ResourceListBean.getResourceItems=function(p0,callback){
dwr.engine._execute(ResourceListBean._path,'ResourceListBean','getResourceItems',p0,false,callback);
}
ResourceListBean.updateResourceItem=function(p0,p1,callback){
dwr.engine._execute(ResourceListBean._path,'ResourceListBean','updateResourceItem',p0,p1,false,callback);
}
ResourceListBean.deleteResourceItem=function(p0,p1,p2,callback){
dwr.engine._execute(ResourceListBean._path,'ResourceListBean','deleteResourceItem',p0,p1,p2,false,callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(RssBean==null)var RssBean={};
RssBean._path='/dwr';
RssBean.getChannel=function(p0,callback){
dwr.engine._execute(RssBean._path,'RssBean','getChannel',p0,callback);
}
RssBean.getItemsOfFeed=function(p0,p1,p2,callback){
dwr.engine._execute(RssBean._path,'RssBean','getItemsOfFeed',p0,p1,p2,callback);
}
RssBean.getRssItemsByTime=function(p0,p1,callback){
dwr.engine._execute(RssBean._path,'RssBean','getRssItemsByTime',p0,p1,callback);
}
RssBean.getCountRssItemsByTime=function(p0,p1,callback){
dwr.engine._execute(RssBean._path,'RssBean','getCountRssItemsByTime',p0,p1,callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(RemindBean==null)var RemindBean={};
RemindBean._path='/dwr';
RemindBean.sendUserMsg=function(p0,p1,p2,callback){
dwr.engine._execute(RemindBean._path,'RemindBean','sendUserMsg',p0,p1,p2,false,callback);
}
RemindBean.getMailCount=function(p0,callback){
dwr.engine._execute(RemindBean._path,'RemindBean','getMailCount',p0,false,callback);
}
RemindBean.getChummies=function(callback){
dwr.engine._execute(RemindBean._path,'RemindBean','getChummies',callback);
}
RemindBean.sendUserMsgWithValcode=function(p0,p1,p2,p3,callback){
dwr.engine._execute(RemindBean._path,'RemindBean','sendUserMsgWithValcode',p0,p1,p2,p3,false,callback);
}
RemindBean.sendShareResource=function(p0,p1,p2,p3,p4,p5,callback){
dwr.engine._execute(RemindBean._path,'RemindBean','sendShareResource',p0,p1,p2,p3,p4,p5,false,callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(UserBean==null)var UserBean={};
UserBean._path='/dwr';
UserBean._udDomain='http://ud.blog.163.com/';
UserBean.check=function(p0,p1,callback){
dwr.engine._execute(UserBean._path,'UserBean','check',p0,p1,false,false,false,callback);
}
UserBean.checkPassport=function(p0,p1,p2,callback){
dwr.engine._execute(UserBean._path,'UserBean','checkPassport',p0,p1,p2,false,false,false,callback);
}
UserBean.checkPassportVN=function(p0,p1,p2,p3,callback){
dwr.engine._execute(UserBean._path,'UserBean','checkPassportVN',p0,p1,p2,p3,false,false,false,callback);
}
UserBean.getGroups=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','getGroups',false,p0,callback);
}
UserBean.getRelation=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','getRelation',p0,callback);
}
UserBean.keepAlive=function(callback){
dwr.engine._execute(UserBean._path,'UserBean','keepAlive',callback);
}
UserBean.setServerName=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','setServerName',p0,callback);
}
UserBean.getServerName=function(callback){
dwr.engine._execute(UserBean._path,'UserBean','getServerName',false,callback);
}
UserBean.addGroup=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','addGroup',false,p0,callback);
}
UserBean.activate=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','activate',p0,callback);
}
UserBean.saveActivateUserInfo=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','saveActivateUserInfo',p0,callback);
}
UserBean.saveBlogTheme=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','saveBlogTheme',p0,callback);
}
UserBean.activatePlayer=function(p0,p1,p2,p3,p4,callback){
dwr.engine._execute(UserBean._path,'UserBean','activatePlayer',p0,p1,p2,p3,p4,callback);
}
UserBean.test=function(callback){
dwr.engine._execute(UserBean._path,'UserBean','test',callback);
}
UserBean.getHostId=function(callback){
dwr.engine._execute(UserBean._path,'UserBean','getHostId',callback);
}
UserBean.getItemsCount=function(p0,p1,callback){
dwr.engine._execute(UserBean._path,'UserBean','getItemsCount',p0,p1,callback);
}
UserBean.getProfileUtil=function(callback){
dwr.engine._execute(UserBean._path,'UserBean','getProfileUtil',callback);
}
UserBean.getProfile=function(callback){
dwr.engine._execute(UserBean._path,'UserBean','getProfile',false,callback);
}
UserBean.getFriends=function(p0,p1,p2,callback){
dwr.engine._execute(UserBean._path,'UserBean','getFriends',false,p0,p1,p2,callback);
}
UserBean.getFriendsByFollowType=function(p0,p1,p2,callback){
dwr.engine._execute(UserBean._path,'UserBean','getFriendsByFollowType',false,p0,p1,p2,callback);
}
UserBean.setMailRemind=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','setMailRemind',p0,callback);
}
UserBean.getUpdateFriends=function(p0,p1,callback){
dwr.engine._execute(UserBean._path,'UserBean','getUpdateFriends',false,p0,p1,callback);
}
UserBean.getUpdateList=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','getUpdateList',p0,callback);
}
UserBean.activateInternal=function(p0,p1,p2,callback){
dwr.engine._execute(UserBean._path,'UserBean','activateInternal',p0,p1,p2,callback);
}
UserBean.getOnLineFriends=function(p0,p1,p2,callback){
dwr.engine._execute(UserBean._path,'UserBean','getOnLineFriends',p0,p1,p2,callback);
}
UserBean.getVisitor=function(p0,p1,p2,callback){
dwr.engine._execute(UserBean._path,'UserBean','getVisitor',false,p0,p1,p2,false,callback);
}
UserBean.getVisitorThroughGet=function(host,p0,p1,p2,callback){
dwr.engine._execute(UserBean._udDomain+host+UserBean._path,'UserBean','getVisitor',false,p0,p1,p2,false,callback);
}
UserBean.getVisitor_inner=function(p0,p1,p2,callback){
dwr.engine._execute(UserBean._path,'UserBean','getVisitor_inner',p0,p1,p2,callback);
}
UserBean.getReferer24HoursCount=function(callback){
dwr.engine._execute(UserBean._path,'UserBean','getReferer24HoursCount',callback);
}
UserBean.getRefererAllCount=function(callback){
dwr.engine._execute(UserBean._path,'UserBean','getRefererAllCount',callback);
}
UserBean.getReferer24Hours=function(p0,p1,callback){
dwr.engine._execute(UserBean._path,'UserBean','getReferer24Hours',p0,p1,callback);
}
UserBean.getRefererAll=function(p0,p1,callback){
dwr.engine._execute(UserBean._path,'UserBean','getRefererAll',p0,p1,callback);
}
UserBean.inviteFriendById=function(p2,p3,p4,callback){
dwr.engine._execute(UserBean._path,'UserBean','inviteFriendById',false,false,p2,p3,p4,callback);
}
UserBean.inviteFriendByIdWithMsg=function(p2,p3,p4,p5,callback){
dwr.engine._execute(UserBean._path,'UserBean','inviteFriendByIdWithMsg',false,false,p2,p3,p4,p5,callback);
}
UserBean.inviteHostWithMsgAndValcode=function(p2,p3,p4,callback){
dwr.engine._execute(UserBean._path,'UserBean','inviteHostWithMsgAndValcode',false,false,p2,p3,p4,callback);
}
UserBean.inviteHost=function(p0,p1,callback){
dwr.engine._execute(UserBean._path,'UserBean','inviteHost',p0,p1,false,false,callback);
}
UserBean.inviteHostWithMsg=function(p0,p1,callback){
dwr.engine._execute(UserBean._path,'UserBean','inviteHostWithMsg',p0,p1,false,false,callback);
}
UserBean.rejectInvite=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','rejectInvite',p0,callback);
}
UserBean.rejectInvites=function(p0,callback){
DWREngine._execute(UserBean._path,'UserBean','rejectInvites',p0,callback);
}
UserBean.acceptFriend=function(p0,p1,callback){
dwr.engine._execute(UserBean._path,'UserBean','acceptFriend',p0,p1,callback);
}
UserBean.acceptFriendWithMsg=function(p1,p2,callback){
dwr.engine._execute(UserBean._path,'UserBean','acceptFriendWithMsg',p1,p2,callback);
}
UserBean.getBasicInfo=function(p0,p1,callback){
dwr.engine._execute(UserBean._path,'UserBean','getBasicInfo',p0,p1,callback);
}
UserBean.acceptFriends=function(p1,p2,callback){
dwr.engine._execute(UserBean._path,'UserBean','acceptFriends',p1,p2,callback);
}
UserBean.getUnAffirmFriends=function(p0,p1,callback){
dwr.engine._execute(UserBean._path,'UserBean','getUnAffirmFriends',p0,p1,callback);
}
UserBean.getInvitingFriends=function(p0,p1,callback){
DWREngine._execute(UserBean._path,'UserBean','getInvitingFriends',p0,p1,callback);
}
UserBean.changeRelation=function(p1,p2,callback){
dwr.engine._execute(UserBean._path,'UserBean','changeRelation',false,p1,p2,callback);
}
UserBean.cancelSentFriendInvitation=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','cancelSentFriendInvitation',p0,callback);
}
UserBean.getProfileMap=function(p0,callback){
DWREngine._execute(UserBean._path,'UserBean','getProfileMap',p0,callback);
}
UserBean.changeFriendsGroup=function(p1,p2,p3,callback){
dwr.engine._execute(UserBean._path,'UserBean','changeFriendsGroup',false,p1,p2,p3,callback);
}
UserBean.removeFriend=function(p0,p1,callback){
dwr.engine._execute(UserBean._path,'UserBean','removeFriend',p0,p1,callback);
}
UserBean.getVisitorCount=function(callback){
dwr.engine._execute(UserBean._path,'UserBean','getVisitorCount',callback);
}
UserBean.getVisiteeCount=function(callback){
dwr.engine._execute(UserBean._path,'UserBean','getVisiteeCount',callback);
}
UserBean.getModuleGroups=function(p1,callback){
dwr.engine._execute(UserBean._path,'UserBean','getModuleGroups',false,p1,callback);
}
UserBean.getVisitorGroups=function(callback){
dwr.engine._execute(UserBean._path,'UserBean','getVisitorGroups',false,callback);
}
UserBean.getInviteEventCount=function(callback){
dwr.engine._execute(UserBean._path,'UserBean','getInviteEventCount',false,callback);
}
UserBean.updateGroup=function(p0,p1,callback){
dwr.engine._execute(UserBean._path,'UserBean','updateGroup',p0,p1,callback);
}
UserBean.updateGroupIdSeq=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','updateGroupIdSeq',p0,callback);
}
UserBean.deleteGroup=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','deleteGroup',p0,callback);
}
UserBean.searchByName=function(p0,p1,p2,p3,callback){
dwr.engine._execute(UserBean._path,'UserBean','searchByName',p0,p1,p2,p3,callback);
}
UserBean.searchExactFriends=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','searchExactFriends',p0,callback);
}
UserBean.getSearchFriendCount=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','getSearchFriendCount',p0,callback);
}
UserBean.searchInviting=function(p0,p1,p2,callback){
dwr.engine._execute(UserBean._path,'UserBean','searchInviting',p0,p1,p2,callback);
}
UserBean.searchInvited=function(p0,p1,p2,callback){
dwr.engine._execute(UserBean._path,'UserBean','searchInvited',p0,p1,p2,callback);
}
UserBean.searchFriends=function(p0,p1,p2,p3,callback){
dwr.engine._execute(UserBean._path,'UserBean','searchFriends',p0,p1,p2,p3,callback);
}
UserBean.searchFollowFriends=function(p0,p1,p2,p3,callback){
dwr.engine._execute(UserBean._path,'UserBean','searchFollowFriends',p0,p1,p2,p3,callback);
}
UserBean.setAuthority=function(p0,p1,p2,p3,p4,p5,p6,callback){
dwr.engine._execute(UserBean._path,'UserBean','setAuthority',p0,p1,p2,p3,p4,p5,p6,false,callback);
}
UserBean.updateMusicSettings=function(p0,p1,callback){
dwr.engine._execute(UserBean._path,'UserBean','updateMusicSettings',p0,p1,false,callback);
}
UserBean.isOnLine=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','isOnLine',p0,callback);
}
UserBean.getVisitInfo=function(callback){
dwr.engine._execute(UserBean._path,'UserBean','getVisitInfo',false,callback);
}
UserBean.getFriendAndFollowStatus=function(callback){
dwr.engine._execute(UserBean._path,'UserBean','getFriendAndFollowStatus',callback);
}
UserBean.updateSpaceName=function(p1,p2,callback){
dwr.engine._execute(UserBean._path,'UserBean','updateSpaceName',false,p1,p2,callback);
}
UserBean.updateSpaceDesc=function(p1,p2,callback){
dwr.engine._execute(UserBean._path,'UserBean','updateSpaceDesc',false,p1,p2,callback);
}
UserBean.canChat=function(callback){
dwr.engine._execute(UserBean._path,'UserBean','canChat',false,callback);
}
UserBean.getListPhotos=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','getListPhotos',p0,callback);
}
UserBean.getAboutMeBasic=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','getAboutMeBasic',p0,false,callback);
}
UserBean.getAboutMe=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','getAboutMe',p0,callback);
}
UserBean.getHostMiniSpace=function(p1,callback){
dwr.engine._execute(UserBean._path,'UserBean','getHostMiniSpace',false,p1,callback);
}
UserBean.updateObserveTime=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','updateObserveTime',p0,callback);
}
UserBean.getWeatherCityCode=function(callback){
dwr.engine._execute(UserBean._path,'UserBean','getWeatherCityCode',false,callback);
}
UserBean.setCookiePath=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','setCookiePath',p0,callback);
}
UserBean.updateRelationTag=function(p0,p1,callback){
dwr.engine._execute(UserBean._path,'UserBean','updateRelationTag',p0,p1,callback);
}
UserBean.setRemindService=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','setRemindService',p0,callback);
}
UserBean.clearSession=function(callback){
dwr.engine._execute(UserBean._path,'UserBean','clearSession',false,false,callback);
}
UserBean.updateORInsertItemsCount=function(p0,p1,p2,p3,callback){
dwr.engine._execute(UserBean._path,'UserBean','updateORInsertItemsCount',p0,p1,p2,p3,callback);
}
UserBean.getProvinceAndCity=function(callback){
dwr.engine._execute(UserBean._path,'UserBean','getProvinceAndCity',false,false,callback);
}
UserBean.setAdvanceSearch=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','setAdvanceSearch',p0,callback);
}
UserBean.getUserImgsArray=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','getUserImgsArray',p0,callback);
}
UserBean.getUserImgsArray=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','getUserImgsArray',p0,callback);
}
UserBean.getProfileById=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','getProfileById',p0,callback);
}
UserBean.getCountInfos=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','getCountInfos',p0,false,callback);
}
UserBean.getFriendList=function(p0,p1,p2,callback){
dwr.engine._execute(UserBean._path,'UserBean','getFriendList',p0,p1,p2,callback);
}
UserBean.getFriendListWithRealName=function(p0,p1,p2,callback){
dwr.engine._execute(UserBean._path,'UserBean','getFriendListWithRealName',p0,p1,p2,callback);
}
UserBean.setHomeType=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','setHomeType',p0,callback);
}
UserBean.checkTargetVerifyRank=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','checkTargetVerifyRank',p0,false,callback);
}
UserBean.updateSingleBlogLayout=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','updateSingleBlogLayout',p0,callback);
}
UserBean.updateChummySettings=function(p0,callback){
dwr.engine._execute(UserBean._path,'UserBean','updateChummySettings',p0,callback);
}
UserBean.getChummies=function(callback){
dwr.engine._execute(UserBean._path,'UserBean','getChummies',callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(BlogBean==null)var BlogBean={};
BlogBean._path='/dwr';
BlogBean._udDomain='http://ud.blog.163.com/';
BlogBean.addClass=function(p0,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','addClass',p0,callback);
}
BlogBean.validSubmitBlogValcode=function(p0,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','validSubmitBlogValcode',p0,false,callback);
}
BlogBean.getRecentComments=function(p0,p1,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','getRecentComments',p0,p1,callback);
}
BlogBean.getCommentsByBlog=function(host,p0,p1,callback){
dwr.engine._execute(BlogBean._udDomain+host+BlogBean._path,'BlogBean','getCommentsByBlog',p0,p1,false,false,callback);
}
BlogBean.getCommentCountByBlog=function(p0,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','getCommentCountByBlog',p0,callback);
}
BlogBean.getBlogCountByBlog=function(p0,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','getBlogCountByBlog',p0,callback);
}
BlogBean.getComments=function(p0,p1,p2,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','getComments',p0,p1,p2,callback);
}
BlogBean.getBlogClasses=function(p0,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','getBlogClasses',p0,callback);
}
BlogBean.getBlogClassesOrdered=function(callback){
dwr.engine._execute(BlogBean._path,'BlogBean','getBlogClassesOrdered',callback);
}
BlogBean.getRecentArchives=function(p0,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','getRecentArchives',p0,callback);
}
BlogBean.getClassesAndArchives=function(p0,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','getClassesAndArchives',p0,callback);
}
BlogBean.getBlogsInPrevBlog=function(p0,p1,p2,p3,p4,p5,p6,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','getBlogsInPrevBlog',p0,p1,p2,p3,p4,p5,p6,callback);
}
BlogBean.getBlogs=function(p0,p1,p2,p3,p4,p5,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','getBlogs',p0,p1,p2,p3,p4,p5,callback);
}
BlogBean.getRecentBlogs=function(p0,p1,p2,p3,p4,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','getRecentBlogs',p0,p1,p2,p3,p4,false,callback);
}
BlogBean.getBlogsByRank=function(p0,p1,p2,p3,p4,p5,p6,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','getBlogsByRank',p0,p1,p2,p3,p4,p5,p6,callback);
}
BlogBean.getBlogsByClassInPrevBlog=function(p0,p1,p2,p3,p4,p5,p6,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','getBlogsByClassInPrevBlog',p0,p1,p2,p3,p4,p5,p6,callback);
}
BlogBean.getBlogsByClass=function(p0,p1,p2,p3,p4,p5,p6,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','getBlogsByClass',p0,p1,p2,p3,p4,p5,p6,callback);
}
BlogBean.getBlogsByClassLite=function(p0,p1,p2,p3,p4,p5,p6,callback){
DWREngine._execute(BlogBean._path,'BlogBean','getBlogsByClassLite',p0,p1,p2,p3,p4,p5,p6,callback);
}
BlogBean.getBlogsByClassByRank=function(p0,p1,p2,p3,p4,p5,p6,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','getBlogsByClassByRank',p0,p1,p2,p3,p4,p5,p6,callback);
}
BlogBean.getBlogsByArchiveInPrevBlog=function(p0,p1,p2,p3,p4,p5,p6,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','getBlogsByArchiveInPrevBlog',p0,p1,p2,p3,p4,p5,p6,callback);
}
BlogBean.getBlogsByArchive=function(p0,p1,p2,p3,p4,p5,p6,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','getBlogsByArchive',p0,p1,p2,p3,p4,p5,p6,callback);
}
BlogBean.getBlog=function(p0,p1,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','getBlog',p0,p1,callback);
}
BlogBean.getBlogsByDate=function(p0,p1,p2,p3,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','getBlogsByDate',p0,p1,p2,p3,callback);
}
BlogBean.updateBlogVisit=function(p0,p1,p2,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','updateBlogVisit',p0,p1,p2,callback);
}
BlogBean.getRecentCommentsByOffset=function(p0,p1,p2,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','getRecentCommentsByOffset',p0,p1,p2,callback);
}
BlogBean.addComment=function(p0,p1,p2,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','addComment',p0,p1,p2,false,callback);
}
BlogBean.getTrackbacks=function(p0,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','getTrackbacks',p0,callback);
}
BlogBean.deleteComment=function(p0,p1,p2,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','deleteComment',p0,p1,p2,callback);
}
BlogBean.deleteCommentForMsg=function(p0,p1,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','deleteCommentForMsg',p0,p1,callback);
}
BlogBean.removeBatchComment=function(p0,p1,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','removeBatchComment',p0,p1,callback);
}
BlogBean.deleteClass=function(p0,p1,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','deleteClass',p0,p1,callback);
}
BlogBean.updateClassByName=function(p0,p1,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','updateClassByName',p0,p1,callback);
}
BlogBean.deleteTrackback=function(p0,p1,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','deleteTrackback',p0,p1,callback);
}
BlogBean.deleteBlog=function(p0,p1,p2,p3,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','deleteBlog',p0,p1,p2,p3,false,callback);
}
BlogBean.getBlogCounts=function(p0,p1,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','getBlogCounts',p0,p1,false,callback);
}
BlogBean.getHostAllTags=function(callback){
dwr.engine._execute(BlogBean._path,'BlogBean','getHostAllTags',false,callback);
}
BlogBean.getRelateBlogsCircles=function(host,p0,p1,callback){
dwr.engine._execute(BlogBean._udDomain+host+BlogBean._path,'BlogBean','getRelateBlogsCircles',p0,p1,false,callback);
}
BlogBean.topBlog=function(p0,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','topBlog',p0,callback);
}
BlogBean.untopBlog=function(p0,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','untopBlog',p0,callback);
}
BlogBean.getBlogsByBidAndUid=function(p0,p1,p2,p3,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','getBlogsByBidAndUid',p0,p1,p2,p3,callback);
}
BlogBean.removeBatchBlogs=function(p0,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','removeBatchBlogs',p0,false,callback);
}
BlogBean.updateClassOfBlogs=function(p0,p1,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','updateClassOfBlogs',p0,p1,callback);
}
BlogBean.updateClassOrderIds=function(p0,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','updateClassOrderIds',p0,callback);
}
BlogBean.glogDistribution=function(p0,p1,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','glogDistribution',p0,p1,callback);
}
BlogBean.isRecomBlog=function(p0,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','isRecomBlog',p0,callback);
}
BlogBean.blogRecommend=function(p0,p1,p2,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','blogRecommend',p0,p1,p2,false,callback);
}
BlogBean.existBlogRecommend=function(p0,callback){;
dwr.engine._execute(BlogBean._path,'BlogBean','existBlogRecommend',p0,callback);
}
BlogBean.getRecentRecommendBlogs=function(p0,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','getRecentRecommendBlogs',p0,false,callback);
}
BlogBean.isBlogerInHomePage=function(p0,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','isBlogerInHomePage',p0,callback);
}
BlogBean.getComment=function(p0,p1,p2,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','getComment',p0,p1,p2,callback);
}
BlogBean.addCommentForMsg=function(p0,callback){
dwr.engine._execute(BlogBean._path,'BlogBean','addCommentForMsg',p0,false,callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(FeelingsBean==null)var FeelingsBean={};
FeelingsBean._path='/dwr';
FeelingsBean._udDomain='http://ud.blog.163.com/';
FeelingsBean.addFeelingsCard=function(p0,callback){
dwr.engine._execute(FeelingsBean._path,'FeelingsBean','addFeelingsCard',p0,false,callback);
}
FeelingsBean.getFirstFeelingsCard=function(callback){
dwr.engine._execute(FeelingsBean._path,'FeelingsBean','getFirstFeelingsCard',false,callback);
}
FeelingsBean.removeFirstFeelingsCard=function(p0,callback){
dwr.engine._execute(FeelingsBean._path,'FeelingsBean','removeFirstFeelingsCard',p0,false,callback);
}
FeelingsBean.getRecentFeelingsCards=function(p0,p1,callback){
dwr.engine._execute(FeelingsBean._path,'FeelingsBean','getRecentFeelingsCards',p0,p1,false,callback);
}
FeelingsBean.removeFeelingsCard=function(p0,callback){
dwr.engine._execute(FeelingsBean._path,'FeelingsBean','removeFeelingsCard',p0,false,callback);
}
FeelingsBean.addFeelingsCardComment=function(p0,p1,callback){
dwr.engine._execute(FeelingsBean._path,'FeelingsBean','addFeelingsCardComment',p0,p1,false,callback);
}
FeelingsBean.getMainCommentCount=function(p0,callback){
dwr.engine._execute(FeelingsBean._path,'FeelingsBean','getMainCommentCount',p0,callback);
}
FeelingsBean.removeFeelingsComment=function(p0,p1,p2,callback){
dwr.engine._execute(FeelingsBean._path,'FeelingsBean','removeFeelingsComment',p0,p1,p2,false,callback);
}
FeelingsBean.removeFeelingsCommentForMsg=function(p0,p1,callback){
dwr.engine._execute(FeelingsBean._path,'FeelingsBean','removeFeelingsCommentForMsg',p0,p1,false,callback);
}
FeelingsBean.getRecentFeelingsComment=function(p0,p1,p2,callback){
dwr.engine._execute(FeelingsBean._path,'FeelingsBean','getRecentFeelingsComment',p0,p1,p2,false,callback);
}
FeelingsBean.getRecentFeelingsComments=function(p0,p1,p2,callback){
dwr.engine._execute(FeelingsBean._path,'FeelingsBean','getRecentFeelingsComments',p0,p1,p2,false,callback);
}
FeelingsBean.getRecentFriendsFeelingCards=function(p0,p1,callback){
dwr.engine._execute(FeelingsBean._path,'FeelingsBean','getRecentFriendsFeelingCards',p0,p1,false,callback);
}
FeelingsBean.getComment=function(p0,p1,p2,callback){
dwr.engine._execute(FeelingsBean._path,'FeelingsBean','getComment',p0,p1,p2,callback);
}
FeelingsBean.addFeelingsCardCommentForMsg=function(p0,callback){
dwr.engine._execute(FeelingsBean._path,'FeelingsBean','addFeelingsCardCommentForMsg',p0,false,callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(NoteBean==null)var NoteBean={};
NoteBean._path='/dwr';
NoteBean.removeNote=function(p0,callback){
dwr.engine._execute(NoteBean._path,'NoteBean','removeNote',p0,callback);
}
NoteBean.getNoteCount=function(callback){
dwr.engine._execute(NoteBean._path,'NoteBean','getNoteCount',callback);
}
NoteBean.addNote=function(p0,p1,callback){
dwr.engine._execute(NoteBean._path,'NoteBean','addNote',p0,p1,false,callback);
}
NoteBean.addNoteToOther=function(p0,p1,callback){
dwr.engine._execute(NoteBean._path,'NoteBean','addNoteToOther',p0,p1,false,callback);
}
NoteBean.removeNotes=function(p0,p1,callback){
dwr.engine._execute(NoteBean._path,'NoteBean','removeNotes',p0,p1,callback);
}
NoteBean.addReply=function(p0,p1,p2,callback){
dwr.engine._execute(NoteBean._path,'NoteBean','addReply',p0,p1,p2,false,callback);
}
NoteBean.getNotesForEdit=function(p0,p1,callback){
dwr.engine._execute(NoteBean._path,'NoteBean','getNotesForEdit',p0,p1,callback);
}
NoteBean.getNotesForPrev=function(p0,p1,callback){
dwr.engine._execute(NoteBean._path,'NoteBean','getNotesForPrev',p0,p1,callback);
}
NoteBean.getNotesForEditProfile=function(p0,p1,callback){
dwr.engine._execute(NoteBean._path,'NoteBean','getNotesForEditProfile',p0,p1,callback);
}
NoteBean.getNotesForPrevProfile=function(p0,p1,callback){
dwr.engine._execute(NoteBean._path,'NoteBean','getNotesForPrevProfile',p0,p1,callback);
}
NoteBean.getRealNoteCount=function(callback){
dwr.engine._execute(NoteBean._path,'NoteBean','getRealNoteCount',callback);
}
NoteBean.getNotesBetweenUsers=function(p0,p1,p2,p3,callback){
dwr.engine._execute(NoteBean._path,'NoteBean','getNotesBetweenUsers',p0,p1,p2,p3,callback);
}
NoteBean.getNoteRankById=function(p0,callback){
dwr.engine._execute(NoteBean._path,'NoteBean','getNoteRankById',p0,callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(MusicBean==null)var MusicBean={};
MusicBean._path='/dwr';
MusicBean.getWapCount=function(callback){
dwr.engine._execute(MusicBean._path,'MusicBean','getWapCount',callback);
}
MusicBean.setWapCount=function(p0,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','setWapCount',p0,callback);
}
MusicBean.getMusicAlbumList=function(p0,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','getMusicAlbumList',p0,callback);
}
MusicBean.getMusicAlbumListByVisit=function(p0,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','getMusicAlbumListByVisit',p0,callback);
}
MusicBean.getMusicAlbumById=function(p0,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','getMusicAlbumById',p0,callback);
}
MusicBean.addMusicAlbum=function(p0,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','addMusicAlbum',p0,false,callback);
}
MusicBean.updateMusicAlbumName=function(p0,p1,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','updateMusicAlbumName',p0,p1,callback);
}
MusicBean.updateMusicAlbumTag=function(p0,p1,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','updateMusicAlbumTag',p0,p1,callback);
}
MusicBean.updateMusicAlbumDescription=function(p0,p1,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','updateMusicAlbumDescription',p0,p1,callback);
}
MusicBean.updateMusicAlbumTop=function(p0,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','updateMusicAlbumTop',p0,callback);
}
MusicBean.updateAlbumStyle=function(p0,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','updateAlbumStyle',p0,callback);
}
MusicBean.updateMusicAlbumStyle=function(p0,p1,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','updateMusicAlbumStyle',p0,p1,callback);
}
MusicBean.deleteMusics=function(p0,p1,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','deleteMusics',p0,p1,callback);
}
MusicBean.deleteMusic=function(p0,p1,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','deleteMusic',p0,p1,callback);
}
MusicBean.deleteMusicAlbum=function(p0,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','deleteMusicAlbum',p0,callback);
}
MusicBean.deleteMusicAlbumPhoto=function(p0,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','deleteMusicAlbumPhoto',p0,callback);
}
MusicBean.getMusicList=function(p0,p1,p2,p3,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','getMusicList',p0,p1,p2,p3,callback);
}
MusicBean.getMusicListByAlbumId=function(p0,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','getMusicListByAlbumId',p0,callback);
}
MusicBean.getPlayList=function(callback){
dwr.engine._execute(MusicBean._path,'MusicBean','getPlayList',callback);
}
MusicBean.addMusic=function(p0,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','addMusic',p0,false,callback);
}
MusicBean.addMusicList=function(p0,p1,p2,p3,p4,p5,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','addMusicList',p0,p1,p2,p3,p4,p5,false,callback);
}
MusicBean.collectMusicAlbum=function(p0,p1,p2,p3,p4,p5,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','collectMusicAlbum',p0,p1,p2,p3,p4,p5,false,callback);
}
MusicBean.collectMusicAlbum=function(p0,p1,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','collectMusicAlbum',p0,p1,callback);
}
MusicBean.getMusicAlbumCollectionCount=function(callback){
dwr.engine._execute(MusicBean._path,'MusicBean','getMusicAlbumCollectionCount',callback);
}
MusicBean.getMusicAlbumCollectionList=function(p0,p1,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','getMusicAlbumCollectionList',p0,p1,callback);
}
MusicBean.deleteMusicAlbumCollection=function(p0,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','deleteMusicAlbumCollection',p0,callback);
}
MusicBean.updateMusic=function(p0,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','updateMusic',p0,false,callback);
}
MusicBean.getOnlineMusicList=function(p0,p1,p2,p3,p4,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','getOnlineMusicList',p0,p1,p2,p3,p4,false,callback);
}
MusicBean.getMusicCommentList=function(p0,p1,p2,p3,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','getMusicCommentList',p0,p1,p2,p3,callback);
}
MusicBean.addMusicComment=function(p0,p1,p2,p3,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','addMusicComment',p0,p1,p2,p3,false,callback);
}
MusicBean.deleteComment=function(p0,p1,p2,p3,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','deleteComment',p0,p1,p2,p3,callback);
}
MusicBean.getMusicAlbumVisitor=function(p0,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','getMusicAlbumVisitor',p0,callback);
}
MusicBean.voteMusicAlbumRank=function(p0,p1,p2,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','voteMusicAlbumRank',p0,p1,p2,callback);
}
MusicBean.updateMusicDuration=function(p0,p1,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','updateMusicDuration',p0,p1,callback);
}
MusicBean.collectMusic=function(p0,p1,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','collectMusic',p0,p1,callback);
}
MusicBean.collectMusicList=function(p0,p1,p2,p3,p4,p5,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','collectMusicList',p0,p1,p2,p3,p4,p5,false,callback);
}
MusicBean.getRecentMusicCommentsByOffset=function(p0,p1,p2,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','getRecentMusicCommentsByOffset',p0,p1,p2,callback);
}
MusicBean.removeBatchComment=function(p0,p1,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','removeBatchComment',p0,p1,callback);
}
MusicBean.addAboutmeMusicComment=function(p0,p1,p2,p3,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','addAboutmeMusicComment',p0,p1,p2,p3,false,callback);
}
MusicBean.getAuditionList=function(callback){
dwr.engine._execute(MusicBean._path,'MusicBean','getAuditionList',false,callback);
}
MusicBean.logAddAuditionList=function(p0,p1,p2,p3,p4,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','logAddAuditionList',p0,p1,p2,p3,p4,false,callback);
}
MusicBean.logDeleteAudition=function(p0,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','logDeleteAudition',p0,false,callback);
}
MusicBean.logClearAuditionList=function(callback){
dwr.engine._execute(MusicBean._path,'MusicBean','logClearAuditionList',false,callback);
}
MusicBean.getComment=function(p0,p1,p2,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','getComment',p0,p1,p2,callback);
}
MusicBean.getMainCommentCount=function(p0,p1,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','getMainCommentCount',p0,p1,callback);
}
MusicBean.deleteCommentForMsg=function(p0,p1,callback){
dwr.engine._execute(MusicBean._path,'MusicBean','deleteCommentForMsg',p0,p1,callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(ModuleTemplateBean==null)var ModuleTemplateBean={};
ModuleTemplateBean._path='/dwr';
ModuleTemplateBean.setGeneratorMap=function(p0,callback){
dwr.engine._execute(ModuleTemplateBean._path,'ModuleTemplateBean','setGeneratorMap',p0,callback);
}
ModuleTemplateBean.generateCommonDataMap=function(callback){
dwr.engine._execute(ModuleTemplateBean._path,'ModuleTemplateBean','generateCommonDataMap',false,callback);
}
ModuleTemplateBean.getEditHtml=function(p0,p1,p2,p3,callback){
dwr.engine._execute(ModuleTemplateBean._path,'ModuleTemplateBean','getEditHtml',p0,p1,p2,p3,false,callback);
}
ModuleTemplateBean.getPreviewHtml=function(p0,p1,p2,p3,callback){
dwr.engine._execute(ModuleTemplateBean._path,'ModuleTemplateBean','getPreviewHtml',p0,p1,p2,p3,false,callback);
}
ModuleTemplateBean.getHtml=function(p0,p1,p2,p3,p4,p5,callback){
dwr.engine._execute(ModuleTemplateBean._path,'ModuleTemplateBean','getHtml',p0,p1,p2,p3,p4,p5,false,callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(PreUserReportBean==null)var PreUserReportBean={};
PreUserReportBean._path='/dwr';
PreUserReportBean.addUserReport=function(p0,callback){
dwr.engine._execute(PreUserReportBean._path,'PreUserReportBean','addUserReport',p0,callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(CustomHtmlBean==null)var CustomHtmlBean={};
CustomHtmlBean._path='/dwr';
CustomHtmlBean.getCustomHtml=function(p0,callback){
dwr.engine._execute(CustomHtmlBean._path,'CustomHtmlBean','getCustomHtml',p0,callback);
}
CustomHtmlBean.addCustomHtml=function(p0,callback){
dwr.engine._execute(CustomHtmlBean._path,'CustomHtmlBean','addCustomHtml',p0,callback);
}
CustomHtmlBean.removeCustomHtml=function(p0,callback){
dwr.engine._execute(CustomHtmlBean._path,'CustomHtmlBean','removeCustomHtml',p0,false,callback);
}
CustomHtmlBean.saveCustomHtml=function(p0,callback){
dwr.engine._execute(CustomHtmlBean._path,'CustomHtmlBean','saveCustomHtml',p0,callback);
}
CustomHtmlBean.addCustomHtmlEx=function(p0,callback){
dwr.engine._execute(CustomHtmlBean._path,'CustomHtmlBean','addCustomHtmlEx',p0,callback);
}
function CustomStyleBean(){}
CustomStyleBean._path='/dwr';
CustomStyleBean.getCustomStyleByUserLimit=function(p0,p1,p2,callback){
DWREngine._execute(CustomStyleBean._path,'CustomStyleBean','getCustomStyleByUserLimit',p0,p1,p2,callback);
}
CustomStyleBean.getCustomStyleByUser=function(p0,callback){
DWREngine._execute(CustomStyleBean._path,'CustomStyleBean','getCustomStyleByUser',p0,callback);
}
CustomStyleBean.getOneCustomStyle=function(p0,p1,p2,callback){
DWREngine._execute(CustomStyleBean._path,'CustomStyleBean','getOneCustomStyle',p0,p1,p2,callback);
}
CustomStyleBean.uploadCustomStyleWithoutPhoto=function(p0,p1,callback){
DWREngine._execute(CustomStyleBean._path,'CustomStyleBean','uploadCustomStyleWithoutPhoto',p0,p1,callback);
}
CustomStyleBean.getNewOneCustomStyle=function(callback){
DWREngine._execute(CustomStyleBean._path,'CustomStyleBean','getNewOneCustomStyle',callback);
}
CustomStyleBean.deleteOneCustomStyle=function(p0,callback){
DWREngine._execute(CustomStyleBean._path,'CustomStyleBean','deleteOneCustomStyle',p0,callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(AdviceBean==null)var AdviceBean={};
AdviceBean._path='/dwr';
AdviceBean.addAdvice=function(p0,callback){
dwr.engine._execute(AdviceBean._path,'AdviceBean','addAdvice',p0,callback);
}
AdviceBean.getCheckedAdviceCount=function(callback){
dwr.engine._execute(AdviceBean._path,'AdviceBean','getCheckedAdviceCount',callback);
}
AdviceBean.getCheckedAdvices=function(p0,p1,callback){
dwr.engine._execute(AdviceBean._path,'AdviceBean','getCheckedAdvices',p0,p1,callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(AlbumMisc==null)var AlbumMisc={};
AlbumMisc._path='/dwr';
AlbumMisc.getRecentComments=function(p0,p1,p2,callback){
dwr.engine._execute(AlbumMisc._path,'AlbumMisc','getRecentComments',p0,p1,p2,false,callback);
}
AlbumMisc.getComments=function(p0,p1,p2,p3,callback){
dwr.engine._execute(AlbumMisc._path,'AlbumMisc','getComments',p0,p1,p2,p3,false,callback);
}
AlbumMisc.checkPassword=function(p0,p1,callback){
dwr.engine._execute(AlbumMisc._path,'AlbumMisc','checkPassword',p0,p1,false,callback);
}
AlbumMisc.addAPComment=function(p0,p1,p2,p3,p4,callback){
dwr.engine._execute(AlbumMisc._path,'AlbumMisc','addAPComment',p0,p1,p2,p3,p4,false,callback);
}
AlbumMisc.addAPComment163=function(p0,p1,p2,p3,callback){
dwr.engine._execute(AlbumMisc._path,'AlbumMisc','addAPComment163',p0,p1,p2,p3,false,callback);
}
AlbumMisc.getAllAPComment=function(p0,p1,p2,p3,callback){
dwr.engine._execute(AlbumMisc._path,'AlbumMisc','getAllAPComment',p0,p1,p2,p3,callback);
}
AlbumMisc.getAPCommentStat=function(p0,p1,callback){
dwr.engine._execute(AlbumMisc._path,'AlbumMisc','getAPCommentStat',p0,p1,callback);
}
AlbumMisc.getAPCommentCount=function(p0,p1,callback){
dwr.engine._execute(AlbumMisc._path,'AlbumMisc','getAPCommentCount',p0,p1,callback);
}
AlbumMisc.getAPComment163List=function(p0,p1,p2,p3,p4,callback){
dwr.engine._execute(AlbumMisc._path,'AlbumMisc','getAPComment163List',p0,p1,p2,p3,p4,callback);
}
AlbumMisc.removeAPComment=function(p0,p1,p2,callback){
dwr.engine._execute(AlbumMisc._path,'AlbumMisc','removeAPComment',p0,p1,p2,false,callback);
}
AlbumMisc.removeAPComment163=function(p0,p1,p2,callback){
dwr.engine._execute(AlbumMisc._path,'AlbumMisc','removeAPComment163',p0,p1,p2,callback);
}
AlbumMisc.updateAPViewCount163=function(p0,p1,p2,callback){
dwr.engine._execute(AlbumMisc._path,'AlbumMisc','updateAPViewCount163',p0,p1,p2,callback);
}
AlbumMisc.updatePhotoViewCount=function(p0,p1,callback){
dwr.engine._execute(AlbumMisc._path,'AlbumMisc','updatePhotoViewCount',p0,p1,callback);
}
AlbumMisc.removePhotoComments=function(p0,p1,callback){
dwr.engine._execute(AlbumMisc._path,'AlbumMisc','removePhotoComments',p0,p1,false,callback);
}
AlbumMisc.removeAlbumComments=function(p0,p1,callback){
dwr.engine._execute(AlbumMisc._path,'AlbumMisc','removeAlbumComments',p0,p1,false,callback);
}
AlbumMisc.updateUAStyle=function(p0,callback){
dwr.engine._execute(AlbumMisc._path,'AlbumMisc','updateUAStyle',p0,false,callback);
}
AlbumMisc.addOrDelTag=function(p0,p1,p2,p3,p4,p5,p6,p7,p8,callback){
dwr.engine._execute(AlbumMisc._path,'AlbumMisc','addOrDelTag',p0,p1,p2,p3,p4,p5,p6,p7,p8,false,callback);
}
AlbumMisc.getDailyStatisticForHome=function(p0,p1,callback){
dwr.engine._execute(AlbumMisc._path,'AlbumMisc','getDailyStatisticForHome',p0,p1,callback);
}
AlbumMisc.getApCommentById=function(p0,p1,callback){
dwr.engine._execute(AlbumMisc._path,'AlbumMisc','getApCommentById',p0,p1,callback);
}
AlbumMisc.addAPCommentForMsg=function(p0,p1,callback){
dwr.engine._execute(AlbumMisc._path,'AlbumMisc','addAPCommentForMsg',p0,p1,false,callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(VisitBean==null)var VisitBean={};
VisitBean._path='/dwr';
VisitBean.getBlogReaders=function(p0,p1,callback){
dwr.engine._execute(VisitBean._path,'VisitBean','getBlogReaders',p0,p1,callback);
}
VisitBean.getBlogReadersArray=function(p0,p1,callback){
dwr.engine._execute(VisitBean._path,'VisitBean','getBlogReadersArray',p0,p1,callback);
}
VisitBean.getPhotoReaders=function(p0,p1,p2,callback){
dwr.engine._execute(VisitBean._path,'VisitBean','getPhotoReaders',p0,p1,p2,callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(PhotoInPaiPaiBean==null)var PhotoInPaiPaiBean={};
PhotoInPaiPaiBean._path='/dwr';
PhotoInPaiPaiBean.getPhotosInPaiPaiByPhotoId=function(p0,callback){
dwr.engine._execute(PhotoInPaiPaiBean._path,'PhotoInPaiPaiBean','getPhotosInPaiPaiByPhotoId',p0,callback);
}
PhotoInPaiPaiBean.setDisplayMode=function(p0,callback){
dwr.engine._execute(PhotoInPaiPaiBean._path,'PhotoInPaiPaiBean','setDisplayMode',p0,callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(AboutMeBean==null)var AboutMeBean={};
AboutMeBean._path='/dwr';
AboutMeBean.getMiddleSchoolCitiesByProvince=function(p0,callback){
dwr.engine._execute(AboutMeBean._path,'AboutMeBean','getMiddleSchoolCitiesByProvince',p0,callback);
}
AboutMeBean.getMiddleSchoolNamesByProvinceCity=function(p0,p1,callback){
dwr.engine._execute(AboutMeBean._path,'AboutMeBean','getMiddleSchoolNamesByProvinceCity',p0,p1,callback);
}
AboutMeBean.getPrimarySchoolCitiesByProvince=function(p0,callback){
dwr.engine._execute(AboutMeBean._path,'AboutMeBean','getPrimarySchoolCitiesByProvince',p0,callback);
}
AboutMeBean.getPrimarySchoolNamesByProvinceCity=function(p0,p1,callback){
dwr.engine._execute(AboutMeBean._path,'AboutMeBean','getPrimarySchoolNamesByProvinceCity',p0,p1,callback);
}
AboutMeBean.getKitSchoolCitiesByProvince=function(p0,callback){
dwr.engine._execute(AboutMeBean._path,'AboutMeBean','getKitSchoolCitiesByProvince',p0,callback);
}
AboutMeBean.getKitSchoolNamesByProvinceCity=function(p0,p1,callback){
dwr.engine._execute(AboutMeBean._path,'AboutMeBean','getKitSchoolNamesByProvinceCity',p0,p1,callback);
}
AboutMeBean.getCityHighSchools=function(p0,callback){
dwr.engine._execute(AboutMeBean._path,'AboutMeBean','getCityHighSchools',p0,callback);
}
AboutMeBean.getHighSchoolRegionByCity=function(p0,callback){
dwr.engine._execute(AboutMeBean._path,'AboutMeBean','getHighSchoolRegionByCity',p0,callback);
}
AboutMeBean.getHighSchoolNamesByCityRegion=function(p0,p1,callback){
dwr.engine._execute(AboutMeBean._path,'AboutMeBean','getHighSchoolNamesByCityRegion',p0,p1,callback);
}
AboutMeBean.getProColleges=function(p0,callback){
dwr.engine._execute(AboutMeBean._path,'AboutMeBean','getProColleges',p0,callback);
}
AboutMeBean.getCollegeNamesByProvince=function(p0,callback){
dwr.engine._execute(AboutMeBean._path,'AboutMeBean','getCollegeNamesByProvince',p0,callback);
}
AboutMeBean.getDepartmentsByProCollege=function(p0,p1,callback){
dwr.engine._execute(AboutMeBean._path,'AboutMeBean','getDepartmentsByProCollege',p0,p1,callback);
}
AboutMeBean.updatePrivacyMap=function(p0,p1,callback){
dwr.engine._execute(AboutMeBean._path,'AboutMeBean','updatePrivacyMap',p0,p1,callback);
}
AboutMeBean.updateAboutMeForMusic=function(p0,p1,p2,callback){
dwr.engine._execute(AboutMeBean._path,'AboutMeBean','updateAboutMeForMusic',p0,p1,p2,callback);
}
AboutMeBean.getSubRegionByProvinceCity=function(p0,p1,callback){
dwr.engine._execute(AboutMeBean._path,'AboutMeBean','getSubRegionByProvinceCity',p0,p1,callback);
}
AboutMeBean.getSubRegionByProvinceCityRegion=function(p0,p1,p2,callback){
dwr.engine._execute(AboutMeBean._path,'AboutMeBean','getSubRegionByProvinceCityRegion',p0,p1,p2,callback);
}
AboutMeBean.addUserDefineSchool=function(p0,p1,p2,p3,p4,p5,callback){
dwr.engine._execute(AboutMeBean._path,'AboutMeBean','addUserDefineSchool',p0,p1,p2,p3,p4,p5,callback);
}
AboutMeBean.passUserDefineSchool=function(p0,callback){
dwr.engine._execute(AboutMeBean._path,'AboutMeBean','passUserDefineSchool',p0,callback);
}
AboutMeBean.unpassUserDefineSchool=function(p0,callback){
dwr.engine._execute(AboutMeBean._path,'AboutMeBean','unpassUserDefineSchool',p0,callback);
}
AboutMeBean.synchSchoolInfoFromActivity=function(p0,callback){
dwr.engine._execute(AboutMeBean._path,'AboutMeBean','synchSchoolInfoFromActivity',p0,callback);
}
AboutMeBean.updateMoodStatus=function(p0,p1,callback){
dwr.engine._execute(AboutMeBean._path,'AboutMeBean','updateMoodStatus',p0,p1,callback);
}
AboutMeBean.updateCityShowStatus=function(p0,p1,callback){
dwr.engine._execute(AboutMeBean._path,'AboutMeBean','updateCityShowStatus',p0,p1,callback);
}
AboutMeBean.addAppProfile=function(p0,callback){
dwr.engine._execute(AboutMeBean._path,'AboutMeBean','addAppProfile',p0,callback);
}
AboutMeBean.updateAboutMe=function(p0,p1,callback){
dwr.engine._execute(AboutMeBean._path,'AboutMeBean','updateAboutMe',p0,p1,callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(PollingBean==null)var PollingBean={};
if(MyMsgBean==null)var MyMsgBean={};
PollingBean._path='http://m.163.com/pl/dwr';
MyMsgBean._path='http://m.163.com/dwr';
PollingBean.pollingMsg=function(p0,p1,callback){
NEPlatform.DwrHook.Switch.shutDownHook();
dwr.engine._execute(PollingBean._path,'PollingBean','pollingMsg',p0,p1,callback);
}
MyMsgBean.updateLoadSysMsgTime=function(p0,callback){
dwr.engine._execute(MyMsgBean._path,'MyMsgBean','updateLoadSysMsgTime',p0,callback);
}
MyMsgBean.getUnReadSysMsgByUserType=function(p0,p1,callback){
dwr.engine._execute(MyMsgBean._path,'MyMsgBean','getUnReadSysMsgByUserType',p0,p1,callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(NewsBean==null)var NewsBean={};
NewsBean._path='/dwr';
NewsBean.getAllOrderedNews=function(callback){
dwr.engine._execute(NewsBean._path,'NewsBean','getAllOrderedNews',callback);
}
NewsBean.updateNewsCode=function(p0,callback){
dwr.engine._execute(NewsBean._path,'NewsBean','updateNewsCode',p0,callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(PlayerBean==null)var PlayerBean={};
PlayerBean._path='/dwr';
PlayerBean.setUserBean=function(p0,callback){
dwr.engine._execute(PlayerBean._path,'PlayerBean','setUserBean',p0,callback);
}
PlayerBean.getPlayerUserName=function(p0,p1,callback){
dwr.engine._execute(PlayerBean._path,'PlayerBean','getPlayerUserName',p0,p1,callback);
}
PlayerBean.activateRole=function(p0,p1,p2,callback){
dwr.engine._execute(PlayerBean._path,'PlayerBean','activateRole',p0,p1,p2,callback);
}
PlayerBean.activatePlayer=function(p0,p1,p2,p3,p4,callback){
dwr.engine._execute(PlayerBean._path,'PlayerBean','activatePlayer',p0,p1,p2,p3,p4,callback);
}
PlayerBean.getActivityService=function(callback){
dwr.engine._execute(PlayerBean._path,'PlayerBean','getActivityService',callback);
}
PlayerBean.setActivityService=function(p0,callback){
dwr.engine._execute(PlayerBean._path,'PlayerBean','setActivityService',p0,callback);
}
PlayerBean.getUserBean=function(callback){
dwr.engine._execute(PlayerBean._path,'PlayerBean','getUserBean',callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(OpenModuleBean==null)var OpenModuleBean={};
OpenModuleBean._path='/dwr';
OpenModuleBean.deleteOpenModule=function(p0,callback){
dwr.engine._execute(OpenModuleBean._path,'OpenModuleBean','deleteOpenModule',p0,false,callback);
}
OpenModuleBean.updatePreference=function(p0,p1,callback){
dwr.engine._execute(OpenModuleBean._path,'OpenModuleBean','updatePreference',p0,p1,callback);
}
OpenModuleBean.createOpenModuleForVisitor=function(p0,callback){
dwr.engine._execute(OpenModuleBean._path,'OpenModuleBean','createOpenModuleForVisitor',p0,callback);
}
OpenModuleBean.processAjaxRequest=function(p0,p1,p2,p3,p4,callback){
dwr.engine._execute(OpenModuleBean._path,'OpenModuleBean','processAjaxRequest',p0,p1,p2,p3,p4,callback);
}
OpenModuleBean.loadOpenModuleContentByUrl=function(p0,p1,callback){
dwr.engine._execute(OpenModuleBean._path,'OpenModuleBean','loadOpenModuleContentByUrl',p0,p1,callback);
}
OpenModuleBean.loadOpenModuleMetaDataByUrl=function(p0,p1,callback){
dwr.engine._execute(OpenModuleBean._path,'OpenModuleBean','loadOpenModuleMetaDataByUrl',p0,p1,callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(WidgetBean==null)var WidgetBean={};
WidgetBean._path='/dwr';
WidgetBean.getComments=function(p0,p1,p2,callback){
dwr.engine._execute(WidgetBean._path,'WidgetBean','getComments',p0,p1,p2,callback);
}
WidgetBean.addComment=function(p0,p1,p2,callback){
dwr.engine._execute(WidgetBean._path,'WidgetBean','addComment',p0,p1,p2,false,callback);
}
WidgetBean.republishWidget=function(p0,p1,callback){
dwr.engine._execute(WidgetBean._path,'WidgetBean','republishWidget',p0,p1,callback);
}
WidgetBean.deleteWidget=function(p0,p1,callback){
dwr.engine._execute(WidgetBean._path,'WidgetBean','deleteWidget',p0,p1,callback);
}
WidgetBean.createWidget=function(p0,p1,callback){
dwr.engine._execute(WidgetBean._path,'WidgetBean','createWidget',p0,p1,callback);
}
WidgetBean.getWidgetAuthor=function(p0,callback){
dwr.engine._execute(WidgetBean._path,'WidgetBean','getWidgetAuthor',p0,callback);
}
WidgetBean.notifyFriends=function(p0,callback){
dwr.engine._execute(WidgetBean._path,'WidgetBean','notifyFriends',p0,callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(PepsiBean==null)var PepsiBean={};
PepsiBean._path='/dwr'
PepsiBean.isAlreadyApplied=function(p0,p1,callback){
dwr.engine._execute(PepsiBean._path,'PepsiBean','isAlreadyApplied',p0,p1,callback);
}
PepsiBean.applyPepsi=function(p0,p1,p2,p3,p4,callback){
dwr.engine._execute(PepsiBean._path,'PepsiBean','applyPepsi',p0,p1,p2,p3,p4,callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(ManageBean==null)var ManageBean={};
ManageBean._path='/dwr';
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(MessagePollingBean==null)var MessagePollingBean={};
if(BlogMessageBean==null)var BlogMessageBean={};
if(MessageCenterBean==null)var MessageCenterBean={};
BlogMessageBean._path='/dwr';
BlogMessageBean._udDomain='http://ud.blog.163.com/';
MessagePollingBean._path='http://blog.163.com/msg/dwr';
MessageCenterBean._path='http://blog.163.com/msg/dwr';
BlogMessageBean.getAPCommentFrom163=function(p0,p1,p2,p3,callback){
dwr.engine.setRpcType(dwr.engine.ScriptTag);
dwr.engine._execute('http://photo.163.com/photo/dwrcross/'+p2+'/u/'+p3+'/dwr','CommentBean','getAPComm',p0,p1,p2,callback);
dwr.engine.setRpcType(dwr.engine.XMLHttpRequest);
}
MessagePollingBean.pollingNewMsg=function(p0,p1,callback){
NEPlatform.DwrHook.Switch.shutDownHook();
dwr.engine.setRpcType(dwr.engine.ScriptTag);
dwr.engine._execute(MessagePollingBean._path,'PollingBean','pollingNewMsg',p0,p1,callback);
dwr.engine.setRpcType(dwr.engine.XMLHttpRequest);
}
MessagePollingBean.getNewMsgCount=function(p0,p1,callback){
dwr.engine.setRpcType(dwr.engine.ScriptTag);
dwr.engine._execute(MessagePollingBean._path,'PollingBean','getNewMsgCount',p0,p1,callback);
dwr.engine.setRpcType(dwr.engine.XMLHttpRequest);
}
MessageCenterBean.sendUserMsg=function(p0,p1,callback){
dwr.engine._execute(MessageCenterBean._path,'MessageBean','sendUserMsg',p0,p1,callback);
}
MessageCenterBean.getUserRecvMsgCount=function(callback){
dwr.engine._execute(MessageCenterBean._path,'MessageBean','getUserRecvMsgCount',callback);
}
MessageCenterBean.getUserRecvMsg=function(p0,p1,callback){
dwr.engine._execute(MessageCenterBean._path,'MessageBean','getUserRecvMsg',p0,p1,callback);
}
MessageCenterBean.deleteUserRecvMsg=function(p0,callback){
dwr.engine._execute(MessageCenterBean._path,'MessageBean','deleteUserRecvMsg',p0,callback);
}
MessageCenterBean.deleteUserSentMsg=function(p0,callback){
dwr.engine._execute(MessageCenterBean._path,'MessageBean','deleteUserSentMsg',p0,callback);
}
MessageCenterBean.getUserSentMsgCount=function(callback){
dwr.engine._execute(MessageCenterBean._path,'MessageBean','getUserSentMsgCount',callback);
}
MessageCenterBean.getUserSentMsg=function(p0,p1,callback){
dwr.engine._execute(MessageCenterBean._path,'MessageBean','getUserSentMsg',p0,p1,callback);
}
MessageCenterBean.getCommentMsg=function(p0,p1,p2,callback){
dwr.engine._execute(MessageCenterBean._path,'MessageBean','getCommentMsg',p0,p1,p2,callback);
}
MessageCenterBean.getCommentMsgCount=function(p0,callback){
dwr.engine._execute(MessageCenterBean._path,'MessageBean','getCommentMsgCount',p0,callback);
}
MessageCenterBean.deleteCommentMsg=function(p0,p1,callback){
dwr.engine._execute(MessageCenterBean._path,'MessageBean','deleteCommentMsg',p0,p1,callback);
}
MessageCenterBean.getAlertMsg=function(p0,p1,p2,callback){
dwr.engine._execute(MessageCenterBean._path,'MessageBean','getAlertMsg',p0,p1,p2,callback);
}
MessageCenterBean.getAlertMsgCount=function(p0,callback){
dwr.engine._execute(MessageCenterBean._path,'MessageBean','getAlertMsgCount',p0,callback);
}
MessageCenterBean.deleteAlertMsg=function(p0,p1,callback){
dwr.engine._execute(MessageCenterBean._path,'MessageBean','deleteAlertMsg',p0,p1,callback);
}
MessageCenterBean.getMsgLoadTimeInfo=function(callback){
dwr.engine._execute(MessageCenterBean._path,'MessageBean','getMsgLoadTimeInfo',callback);
}
MessageCenterBean.getMsgHistoryCount=function(p0,callback){
dwr.engine._execute(MessageCenterBean._path,'MessageBean','getMsgHistoryCount',p0,callback);
}
MessageCenterBean.getUserMsgHistory=function(p0,p1,p2,callback){
dwr.engine._execute(MessageCenterBean._path,'MessageBean','getUserMsgHistory',p0,p1,p2,callback);
}
MessageCenterBean.replyMsg=function(p0,p1,p2,callback){
dwr.engine._execute(MessageCenterBean._path,'MessageBean','replyMsg',p0,p1,p2,callback);
}
MessageCenterBean.getNewBulletinCount=function(callback){
dwr.engine._execute(MessageCenterBean._path,'MessageBean','getNewBulletinCount',callback);
}
MessageCenterBean.getRecentBulletins=function(callback){
dwr.engine._execute(MessageCenterBean._path,'MessageBean','getRecentBulletins',callback);
}
MessageCenterBean.getTopBulletins=function(callback){
dwr.engine._execute(MessageCenterBean._path,'MessageBean','getTopBulletins',callback);
}
MessageCenterBean.clearMsgRecv=function(callback){
dwr.engine._execute(MessageCenterBean._path,'MessageBean','clearMsgRecv',callback);
}
MessageCenterBean.clearMsgSent=function(callback){
dwr.engine._execute(MessageCenterBean._path,'MessageBean','clearMsgSent',callback);
}
MessageCenterBean.clearAlertMsg=function(callback){
dwr.engine._execute(MessageCenterBean._path,'MessageBean','clearAlertMsg',callback);
}
MessageCenterBean.updateAlertRC=function(p0,p1,p2,callback){
dwr.engine._execute(MessageCenterBean._path,'MessageBean','updateAlertRC',p0,p1,p2,callback);
}
MessageCenterBean.addReplyComment=function(p0,p1,callback){
dwr.engine._execute(MessageCenterBean._path,'MessageBean','addReplyComment',p0,p1,callback);
}
MessageCenterBean.acceptFriend=function(p0,p1,p2,callback){
dwr.engine._execute(MessageCenterBean._path,'MessageBean','acceptFriend',p0,p1,p2,callback);
}
MessageCenterBean.rejectFriendInvite=function(p0,p1,callback){
dwr.engine._execute(MessageCenterBean._path,'MessageBean','rejectFriendInvite',p0,p1,callback);
}
MessageCenterBean.acceptCircleInvitation=function(p0,p1,callback){
dwr.engine._execute(MessageCenterBean._path,'MessageBean','acceptCircleInvitation',p0,p1,callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(UserFollowBean==null)var UserFollowBean={};
UserFollowBean._path='/dwr';
UserFollowBean.getFollowingFriends=function(p0,callback){
dwr.engine._execute(UserFollowBean._path,'UserFollowBean','getFollowingFriends',p0,{callback:callback,
errorHandler:function(errMsg,ex){dwrlog('系统出错，请刷新重试','error');}
});
};
UserFollowBean.getNonFollowingFriends=function(callback){
dwr.engine._execute(UserFollowBean._path,'UserFollowBean','getNonFollowingFriends',{callback:callback,
errorHandler:function(errMsg,ex){dwrlog('系统出错，请刷新重试','error');}
});
};
UserFollowBean.getNonFollowingFriendsDetail=function(callback){
dwr.engine._execute(UserFollowBean._path,'UserFollowBean','getNonFollowingFriendsDetail',{callback:callback,
errorHandler:function(errMsg,ex){dwrlog('系统出错，请刷新重试','error');}
});
};
UserFollowBean.changeFriendFollowing=function(p0,p1,callback){
dwr.engine._execute(UserFollowBean._path,'UserFollowBean','changeFriendFollowing',p0,p1,{callback:callback,
errorHandler:function(errMsg,ex){dwrlog('系统出错，请刷新重试','error');}
});
};
UserFollowBean.getFollowingData=function(callback){
dwr.engine._execute(UserFollowBean._path,'UserFollowBean','getFollowingData',{callback:callback,
errorHandler:function(errMsg,ex){if(errMsg!="Timeout"||ex.name!="dwr.engine.timeout")dwrlog('系统出错，请刷新重试','error');}
});
};
UserFollowBean.getFriendsInfo=function(p0,callback){
dwr.engine._execute(UserFollowBean._path,'UserFollowBean','getFriendsInfo',p0,{callback:callback,
errorHandler:function(errMsg,ex){dwrlog('系统出错，请刷新重试','error');}
});
};
UserFollowBean.followUser=function(p0,callback){
dwr.engine._execute(UserFollowBean._path,'UserFollowBean','followUser',p0,{callback:callback,
errorHandler:function(errMsg,ex){dwrlog('系统出错，请刷新重试','error');}
});
};
UserFollowBean.cancelFollowUser=function(p0,callback){
dwr.engine._execute(UserFollowBean._path,'UserFollowBean','cancelFollowUser',p0,{callback:callback,
errorHandler:function(errMsg,ex){dwrlog('系统出错，请刷新重试','error');}
});
};
UserFollowBean.getNormalFollowingUsers=function(p0,p1,callback){
dwr.engine._execute(UserFollowBean._path,'UserFollowBean','getNormalFollowingUsers',p0,p1,{callback:callback,
errorHandler:function(errMsg,ex){dwrlog('系统出错，请刷新重试','error');}
});
};
UserFollowBean.searchNormalFollowingUsers=function(p0,p1,p2,callback){
dwr.engine._execute(UserFollowBean._path,'UserFollowBean','searchNormalFollowingUsers',p0,p1,p2,{callback:callback,
errorHandler:function(errMsg,ex){dwrlog('系统出错，请刷新重试','error');}
});
};
UserFollowBean.getNormalFollowedUsers=function(p0,p1,callback){
dwr.engine._execute(UserFollowBean._path,'UserFollowBean','getNormalFollowedUsers',p0,p1,{callback:callback,
errorHandler:function(errMsg,ex){dwrlog('系统出错，请刷新重试','error');}
});
};
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(NewResourceBean==null)var NewResourceBean={};
NewResourceBean._path='/dwr';
NewResourceBean.getBlogRecommends=function(p0,p1,p2,callback){
dwr.engine._execute(NewResourceBean._path,'NewResourceBean','getBlogRecommends',p0,p1,p2,callback);
}
NewResourceBean.removeBlogRecommend=function(p0,callback){
dwr.engine._execute(NewResourceBean._path,'NewResourceBean','removeBlogRecommend',p0,callback);
}
NewResourceBean.getBookmarkItems=function(p0,callback){
dwr.engine._execute(NewResourceBean._path,'NewResourceBean','getBookmarkItems',p0,callback);
}
NewResourceBean.addBookmarkItem=function(p0,callback){
dwr.engine._execute(NewResourceBean._path,'NewResourceBean','addBookmarkItem',p0,callback);
}
NewResourceBean.deleteBookmarkItem=function(p0,p1,callback){
dwr.engine._execute(NewResourceBean._path,'NewResourceBean','deleteBookmarkItem',p0,p1,callback);
}
NewResourceBean.updateBookmarkItem=function(p0,callback){
dwr.engine._execute(NewResourceBean._path,'NewResourceBean','updateBookmarkItem',p0,callback);
}
NewResourceBean.getBookmarkLists=function(callback){
dwr.engine._execute(NewResourceBean._path,'NewResourceBean','getBookmarkLists',callback);
}
NewResourceBean.addBookmarkList=function(p0,callback){
dwr.engine._execute(NewResourceBean._path,'NewResourceBean','addBookmarkList',p0,callback);
}
NewResourceBean.deleteBookmarkList=function(p0,callback){
dwr.engine._execute(NewResourceBean._path,'NewResourceBean','deleteBookmarkList',p0,false,callback);
}
NewResourceBean.updateBookmarkList=function(p0,callback){
dwr.engine._execute(NewResourceBean._path,'NewResourceBean','updateBookmarkList',p0,false,callback);
}
NewResourceBean.updateBookmarkSequence=function(p0,p1,callback){
NEPlatform.DwrHook.Switch.shutDownHook();
dwr.engine._execute(NewResourceBean._path,'NewResourceBean','updateBookmarkSequence',p0,p1,callback);
}
NewResourceBean.updateBookmarkListSequence=function(p0,callback){
NEPlatform.DwrHook.Switch.shutDownHook();
dwr.engine._execute(NewResourceBean._path,'NewResourceBean','updateBookmarkListSequence',p0,callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(BgsBean==null)var BgsBean={};
BgsBean._path='http://blog.163.com/bgs/dwr';
BgsBean.getBgsUserByUserId=function(p0,callback){
NEPlatform.DwrHook.Switch.shutDownHook();
dwr.engine._execute(BgsBean._path,'BgsBean','getBgsUserByUserId',p0,false,callback);
};
