if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(DiyMusicBean==null)var DiyMusicBean={};
DiyMusicBean._path='/dwr';
DiyMusicBean.deleteMusic=function(p0,p1,callback){
dwr.engine._execute(DiyMusicBean._path,'DiyMusicBean','deleteMusic',p0,p1,callback);
}
DiyMusicBean.deleteMusics=function(p0,p1,callback){
dwr.engine._execute(DiyMusicBean._path,'DiyMusicBean','deleteMusics',p0,p1,callback);
}
DiyMusicBean.getMusicListViewAll=function(p0,p1,callback){
dwr.engine._execute(DiyMusicBean._path,'DiyMusicBean','getMusicListViewAll',p0,p1,callback);
}
DiyMusicBean.getMusicList=function(p0,p1,callback){
dwr.engine._execute(DiyMusicBean._path,'DiyMusicBean','getMusicList',p0,p1,callback);
}
DiyMusicBean.updateMusicName=function(p0,p1,callback){
dwr.engine._execute(DiyMusicBean._path,'DiyMusicBean','updateMusicName',p0,p1,callback);
}
DiyMusicBean.updateMusicIntroduction=function(p0,p1,callback){
dwr.engine._execute(DiyMusicBean._path,'DiyMusicBean','updateMusicIntroduction',p0,p1,callback);
}
DiyMusicBean.updateMusicLyric=function(p0,p1,callback){
dwr.engine._execute(DiyMusicBean._path,'DiyMusicBean','updateMusicLyric',p0,p1,callback);
}
DiyMusicBean.updateMusicPrivacy=function(p0,p1,p2,p3,callback){
dwr.engine._execute(DiyMusicBean._path,'DiyMusicBean','updateMusicPrivacy',p0,p1,p2,p3,callback);
}
DiyMusicBean.voteMusicRank=function(p0,p1,callback){
dwr.engine._execute(DiyMusicBean._path,'DiyMusicBean','voteMusicRank',p0,p1,callback);
}
DiyMusicBean.voteMusicStyleRank=function(p0,callback){
dwr.engine._execute(DiyMusicBean._path,'DiyMusicBean','voteMusicStyleRank',p0,callback);
}
DiyMusicBean.getDownloadUrl=function(p0,callback){
dwr.engine._execute(DiyMusicBean._path,'DiyMusicBean','getDownloadUrl',p0,callback);
}
DiyMusicBean.collectDiyMusic=function(p0,p1,callback){
dwr.engine._execute(DiyMusicBean._path,'DiyMusicBean','collectDiyMusic',p0,p1,callback);
}
DiyMusicBean.checkAuthor=function(p0,callback){
dwr.engine._execute(DiyMusicBean._path,'DiyMusicBean','checkAuthor',p0,callback);
}
DiyMusicBean.getMusicCommentList=function(p0,p1,p2,p3,callback){
dwr.engine._execute(DiyMusicBean._path,'DiyMusicBean','getMusicCommentList',p0,p1,p2,p3,callback);
}
DiyMusicBean.getMainCommentCount=function(p0,p1,callback){
dwr.engine._execute(DiyMusicBean._path,'DiyMusicBean','getMainCommentCount',p0,p1,callback);
}
DiyMusicBean.addMusicComment=function(p0,p1,p2,p3,callback){
dwr.engine._execute(DiyMusicBean._path,'DiyMusicBean','addMusicComment',p0,p1,p2,p3,false,callback);
}
DiyMusicBean.deleteComment=function(p0,p1,p2,p3,callback){
dwr.engine._execute(DiyMusicBean._path,'DiyMusicBean','deleteComment',p0,p1,p2,p3,callback);
}
DiyMusicBean.getDiyMusicVisitor=function(callback){
dwr.engine._execute(DiyMusicBean._path,'DiyMusicBean','getDiyMusicVisitor',callback);
}
DiyMusicBean.addMusicCommentMsgCenter=function(p0,callback){
dwr.engine._execute(DiyMusicBean._path,'DiyMusicBean','addMusicCommentMsgCenter',p0,false,callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(Album==null)var Album={};
Album._path='/dwr';
Album.getAllAlbumsInUser=function(p0,callback){
dwr.engine._execute(Album._path,'Album','getAllAlbumsInUser',p0,false,callback);
}
Album.getAlbumById=function(p0,callback){
dwr.engine._execute(Album._path,'Album','getAlbumById',p0,callback);
}
Album.addNewAlbumNoTag=function(p0,p1,p2,callback){
dwr.engine._execute(Album._path,'Album','addNewAlbumNoTag',p0,p1,p2,false,callback);
}
Album.addNewAlbum=function(p0,p1,p2,p3,p4,callback){
dwr.engine._execute(Album._path,'Album','addNewAlbum',p0,p1,p2,p3,p4,false,callback);
}
Album.setAlbumPassword=function(p0,p1,callback){
dwr.engine._execute(Album._path,'Album','setAlbumPassword',p0,p1,false,callback);
}
Album.deleteAlbum=function(p0,callback){
dwr.engine._execute(Album._path,'Album','deleteAlbum',p0,false,callback);
}
Album.getAlbumsFromPhoto=function(p0,callback){
dwr.engine._execute(Album._path,'Album','getAlbumsFromPhoto',p0,false,callback);
}
Album.movePhotoToAlbum=function(p0,p1,callback){
dwr.engine._execute(Album._path,'Album','movePhotoToAlbum',p0,p1,false,callback);
}
Album.getAlbumOperateService=function(callback){
dwr.engine._execute(Album._path,'Album','getAlbumOperateService',callback);
}
Album.removePhotoFromAlbum=function(p0,p1,callback){
dwr.engine._execute(Album._path,'Album','removePhotoFromAlbum',p0,p1,false,callback);
}
Album.resetAlbumPassword=function(p0,callback){
dwr.engine._execute(Album._path,'Album','resetAlbumPassword',p0,false,callback);
}
Album.updateAlbum=function(p0,p1,p2,p3,callback){
dwr.engine._execute(Album._path,'Album','updateAlbum',p0,p1,p2,p3,false,callback);
}
Album.updateAlbumPassword=function(p0,p1,callback){
dwr.engine._execute(Album._path,'Album','updateAlbumPassword',p0,p1,callback);
}
Album.updateAlbumCover=function(p0,p1,callback){
dwr.engine._execute(Album._path,'Album','updateAlbumCover',p0,p1,false,callback);
}
Album.getAllAlbumsInUserEx=function(p0,callback){
dwr.engine._execute(Album._path,'Album','getAllAlbumsInUserEx',p0,false,callback);
}
Album.addAlb2Favo=function(p0,callback){
dwr.engine._execute(Album._path,'Album','addAlb2Favo',p0,callback);
}
Album.removeAlbFavo=function(p0,p1,callback){
dwr.engine._execute(Album._path,'Album','removeAlbFavo',p0,p1,callback);
}
Album.getAlbInFavo=function(p0,p1,callback){
dwr.engine._execute(Album._path,'Album','getAlbInFavo',p0,p1,false,callback);
}
Album.cleanAlbumsInFavority=function(callback){
dwr.engine._execute(Album._path,'Album','cleanAlbumsInFavority',callback);
}
Album.updateAlbumPrivacy=function(p0,p1,callback){
dwr.engine._execute(Album._path,'Album','updateAlbumPrivacy',p0,p1,false,callback);
}
Album.checkAlbumPassword=function(p0,p1,callback){
dwr.engine._execute(Album._path,'Album','checkAlbumPassword',p0,p1,false,callback);
}
Album.getUnassortedAlbum=function(callback){
dwr.engine._execute(Album._path,'Album','getUnassortedAlbum',callback);
}
Album.changePhotosAlbum=function(p0,p1,p2,callback){
dwr.engine._execute(Album._path,'Album','changePhotosAlbum',p0,p1,p2,callback);
}
Album.updateAlbumAccessCount=function(p0,callback){
dwr.engine._execute(Album._path,'Album','updateAlbumAccessCount',p0,callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(UploadMonitorBean==null)var UploadMonitorBean={};
UploadMonitorBean._path='/dwr';
UploadMonitorBean.getUploadInfo=function(callback){
dwr.engine._execute(UploadMonitorBean._path,'UploadMonitorBean','getUploadInfo',callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(BlogList==null)var BlogList={};
BlogList._path='/dwr';
BlogList.setCount=function(p0,callback){
dwr.engine._execute(BlogList._path,'BlogList','setCount',p0,callback);
}
BlogList.getRecentBlogInfo=function(p1,callback){
dwr.engine._execute(BlogList._path,'BlogList','getRecentBlogInfo',false,p1,callback);
}
BlogList.getRecentBlogInfoMap=function(p1,p2,callback){
dwr.engine._execute(BlogList._path,'BlogList','getRecentBlogInfoMap',false,p1,p2,callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(TagBean==null)var TagBean={};
TagBean._path='/dwr';
TagBean.searchBlog=function(p0,p1,p2,p3,p4,p5,callback){
dwr.engine._execute(TagBean._path,'TagBean','searchBlog',p0,p1,p2,p3,p4,p5,callback);
}
TagBean.searchPhoto=function(p0,p1,p2,p3,p4,p5,callback){
dwr.engine._execute(TagBean._path,'TagBean','searchPhoto',p0,p1,p2,p3,p4,p5,callback);
}
TagBean.searchList=function(p0,p1,p2,p3,p4,p5,callback){
dwr.engine._execute(TagBean._path,'TagBean','searchList',p0,p1,p2,p3,p4,p5,callback);
}
TagBean.getHostAllTags=function(callback){
dwr.engine._execute(TagBean._path,'TagBean','getHostAllTags',false,callback);
}
TagBean.getGlobalTag=function(p0,p1,callback){
dwr.engine._execute(TagBean._path,'TagBean','getGlobalTag',p0,p1,callback);
}
TagBean.searchSuggest=function(p0,p1,p2,callback){
dwr.engine._execute(TagBean._path,'TagBean','searchSuggest',p0,p1,p2,callback);
}
TagBean.searchTagAll=function(p0,p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,callback){
dwr.engine._execute(TagBean._path,'TagBean','searchTagAll',p0,p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,callback);
}
TagBean.addTag=function(p0,callback){
dwr.engine._execute(TagBean._path,'TagBean','addTag',p0,false,callback);
}
TagBean.structUserTags=function(callback){
dwr.engine._execute(TagBean._path,'TagBean','structUserTags',false,callback);
}
TagBean.setNeedRefresh=function(p0,p1,p2,p3,callback){
dwr.engine._execute(TagBean._path,'TagBean','setNeedRefresh',p0,p1,p2,p3,false,callback);
}
TagBean.structResourceTags=function(p0,p1,callback){
dwr.engine._execute(TagBean._path,'TagBean','structResourceTags',p0,p1,callback);
}
TagBean.updateTagnameInUser=function(p0,p1,callback){
dwr.engine._execute(TagBean._path,'TagBean','updateTagnameInUser',p0,p1,false,callback);
}
TagBean.clearTagResourseInUser=function(p0,p1,callback){
dwr.engine._execute(TagBean._path,'TagBean','clearTagResourseInUser',p0,p1,false,callback);
}
TagBean.addTagResourceBatch=function(p0,p1,p2,p3,p4,p5,callback){
dwr.engine._execute(TagBean._path,'TagBean','addTagResourceBatch',p0,p1,p2,p3,p4,p5,false,callback);
}
if(dwr==null)var dwr={};
if(dwr.engine==null)dwr.engine={};
if(DWREngine==null)var DWREngine=dwr.engine;
if(YoudaoBean==null)var YoudaoBean={};
YoudaoBean._path='/dwr';
YoudaoBean._udDomain='http://ud.blog.163.com/';
YoudaoBean.getPostSense=function(host,p0,p1,p2,callback){
dwr.engine._execute(YoudaoBean._udDomain+host+YoudaoBean._path,'YoudaoBean','getPostSense',p0,p1,p2,false,false,callback);
}
