//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SockProxy.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SOCKPROXY_DIALOG            102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDC_USER                        1000
#define IDC_PASS                        1001
#define IDC_SERVER                      1002
#define IDC_PORT                        1003
#define IDC_TEST                        1004
#define IDC_DEST                        1005
#define IDC_PORT2                       1006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
