NeeqThread: config_env.h  config_posix.h  event_id.h  main.cpp  my_thread.h  thread.cpp  thread.h  thread_mutex.cpp  thread_mutex.h  util.cpp  util.h
	g++ -g -o NeeqThread main.cpp  thread.cpp  thread_mutex.cpp  util.cpp  -lpthread
clean:
	rm NeeqThread
