//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ChatClient.rc
//
#define IDR_CNTR_INPLACE                6
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDC_SEND                        101
#define IDP_FAILED_TO_CREATE            102
#define IDC_ONLINE                      102
#define IDD_SENDDLG                     103
#define CG_IDS_SOCKETS_INIT_FAILED      104
#define IDR_MAINFRAME                   128
#define IDR_CHATCLTYPE                  129
#define IDD_ONLINEDLG                   131
#define IDB_IMAGE                       132
#define IDD_SETUP                       133
#define IDC_NAME                        1002
#define IDC_SERVER                      1003
#define IDC_IMAGE                       1004
#define IDC_TO                          1005
#define IDC_TYPE                        1007
#define IDC_SECRET                      1008
#define IDC_FILTER                      1009
#define IDC_TEXT                        1010
#define IDC_COLOR                       1011
#define ID_CANCEL_EDIT_CNTR             32768
#define IDC_CONNECT                     32771
#define IDC_DISCONNECT                  32772
#define IDS_TALK0                       61204
#define IDS_TALK1                       61205
#define IDS_TALK2                       61206
#define IDS_TALK3                       61207
#define IDS_TALK4                       61208
#define IDS_TALK5                       61209
#define IDS_TALK6                       61210
#define IDS_TALK7                       61211
#define IDS_TALK8                       61212
#define IDS_TALK9                       61213
#define IDS_TALK10                      61214
#define IDS_TALK11                      61215
#define IDS_TALK12                      61216
#define IDS_TALK13                      61217
#define IDS_TALK14                      61218
#define IDS_TALK15                      61219
#define IDS_TALK16                      61220
#define IDS_TALK17                      61221
#define IDS_TALK18                      61222
#define IDS_TALK19                      61223
#define IDS_TALK20                      61224
#define IDS_TALK21                      61225
#define IDS_TALK22                      61226
#define IDS_TALK23                      61227
#define IDS_TALK24                      61228
#define IDS_TALK25                      61229
#define IDS_TALK26                      61230
#define IDS_TALK27                      61231
#define IDS_TALK28                      61232
#define IDS_TALK29                      61233
#define IDS_TALK30                      61234
#define IDS_TALK31                      61235
#define IDS_TALK32                      61236
#define IDS_S0                          61250
#define IDS_S1                          61251
#define IDS_S2                          61252
#define IDS_S3                          61253
#define IDS_S4                          61254
#define IDS_S5                          61255
#define IDS_S6                          61256
#define IDS_S7                          61257
#define IDS_S8                          61258
#define IDS_S9                          61259
#define IDS_S10                         61260
#define IDS_S11                         61261
#define IDS_S12                         61262
#define IDS_S13                         61263
#define IDS_S14                         61264
#define IDS_S15                         61265
#define IDS_S16                         61266
#define IDS_S17                         61267
#define IDS_S18                         61268
#define IDS_S19                         61269
#define IDS_S20                         61270
#define IDS_S21                         61271
#define IDS_S22                         61272
#define IDS_S23                         61273
#define IDS_S24                         61274
#define IDS_S25                         61275
#define IDS_S26                         61276
#define IDS_S27                         61277
#define IDS_S28                         61278
#define IDS_S29                         61279
#define IDS_S30                         61280
#define IDS_S31                         61281
#define IDS_S32                         61282
#define IDS_RETRYCONNECT                61446
#define IDS_SERVERRESET                 61447
#define IDC_LISTBOX                     61448
#define IDS_CONNECTIONCLOSED            61449

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1012
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
