/********************************************************************
  Purpose:	Declaration of CDemoDCOM. Skeleton of this file is generated by the Add ATL Project wizard.
            Manually edited to support ISupportErrorInfo.

  Created:	6 8, 2009
  Author:	Yalon Lotan
*********************************************************************/
#pragma once

#include "DemoServer_i.h"

#if defined(_WIN32_WCE) && !defined(_CE_DCOM) && !defined(_CE_ALLOW_SINGLE_THREADED_OBJECTS_IN_MTA)
#error "Single-threaded COM objects are not properly supported on Windows CE platform, such as the Windows Mobile platforms that do not include full DCOM support. Define _CE_ALLOW_SINGLE_THREADED_OBJECTS_IN_MTA to force ATL to support creating single-thread COM object's and allow use of it's single-threaded COM object implementations. The threading model in your rgs file was set to 'Free' as that is the only threading model supported in non DCOM Windows CE platforms."
#endif

class ATL_NO_VTABLE CDemoDCOM :
	public CComObjectRootEx<CComSingleThreadModel>,
	public CComCoClass<CDemoDCOM, &CLSID_DemoDCOM>,
    public ISupportErrorInfo,
	public IDispatchImpl<IDemoDCOM, &IID_IDemoDCOM, &LIBID_DemoServerLib, /*wMajor =*/ 1, /*wMinor =*/ 0>
{
public:
	CDemoDCOM()	{}

DECLARE_REGISTRY_RESOURCEID(IDR_DEMODCOM)


BEGIN_COM_MAP(CDemoDCOM)
	COM_INTERFACE_ENTRY(IDemoDCOM)
    COM_INTERFACE_ENTRY(ISupportErrorInfo)
	COM_INTERFACE_ENTRY(IDispatch)
END_COM_MAP()

	DECLARE_PROTECT_FINAL_CONSTRUCT()

	HRESULT FinalConstruct() { return S_OK;	}

	void FinalRelease() {}

public:
    STDMETHOD(DoSomethingRemote)(void);

    // ISupportsErrorInfo
    STDMETHOD(InterfaceSupportsErrorInfo)(REFIID riid);
};

OBJECT_ENTRY_AUTO(__uuidof(DemoDCOM), CDemoDCOM)
