// COM4Dbg.idl : IDL source for COM4Dbg.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (COM4Dbg.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(7A30E1D0-7CCD-45BD-98AF-F2F9E0B90FC7),
		dual,
		helpstring("ISimpleCOM Interface"),
		pointer_default(unique)
	]
	interface ISimpleCOM : IDispatch
	{
		[id(1), helpstring("method Plus")] HRESULT Plus([in] double dX, [in] double dY, [out] double* dRet);
		[id(2), helpstring("method StrComp")] HRESULT StrComp([in]BSTR bstr);
	};

[
	uuid(3E830A6A-152C-4F67-9537-91E07AD5EC24),
	version(1.0),
	helpstring("COM4Dbg 1.0 Type Library")
]
library COM4DBGLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(196E4BE1-9321-4DC3-BAFA-EA5B1BFF4872),
		helpstring("SimpleCOM Class")
	]
	coclass SimpleCOM
	{
		[default] interface ISimpleCOM;
	};
};
