(function(){
var h=true,i=null,m=false,aa=(new Date).getTime(),ba=function(a){var b=(new Date).getTime()-aa,c="&dtd="+(b<1000?b:"M");return a+c};var n=this,ca=function(a,b,c){var d=a.split("."),e=c||n;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(var f;d.length&&(f=d.shift());)if(!d.length&&b!==undefined)e[f]=b;else e=e[f]?e[f]:(e[f]={})},o=function(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";
if(!(a instanceof Object)&&(Object.prototype.toString.call(a)=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call")))return"function"}else return"null";else if(b=="function"&&typeof a.call=="undefined")return"object";return b},p=function(a){return o(a)=="array"},da=function(a){var b=o(a);return b=="array"||b=="object"&&typeof a.length=="number"},q=function(a){return typeof a=="string"},ea=function(a){var b=o(a);return b=="object"||
b=="array"||b=="function"};Math.floor(Math.random()*2147483648).toString(36);
var fa=function(a){var b=o(a);if(b=="object"||b=="array"){if(a.clone)return a.clone.call(a);var c=b=="array"?[]:{};for(var d in a)c[d]=fa(a[d]);return c}return a},ga=function(a,b){var c=a.v;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);c&&d.unshift.apply(d,c);c=d}b=a.z||b;a=a.w||a;var e,f=b||n;e=c?function(){var g=Array.prototype.slice.call(arguments);g.unshift.apply(g,c);return a.apply(f,g)}:function(){return a.apply(f,arguments)};e.v=c;e.z=b;e.w=a;return e},ha=Date.now||function(){return(new Date).getTime()},
r=function(a,b,c){ca(a,b,c)};function t(a,b){var c=parseFloat(a);return isNaN(c)||c>1||c<0?b:c}function u(a,b){if(a=="true")return h;if(a=="false")return m;return b}function w(a,b){var c=/^([\w-]+\.)+[\w-]{2,}(\:[0-9]+)?$/;return c.test(a)?a:b};var ia="pagead2.googlesyndication.com",ja="googleads.g.doubleclick.net",ka="pubads.g.doubleclick.net",la="securepubads.g.doubleclick.net",ma="partner.googleadservices.com",x=w("pagead2.googlesyndication.com",ia),na=w("googleads.g.doubleclick.net",ja),oa=w("pagead2.googlesyndication.com",ia);w("pubads.g.doubleclick.net",ka);w("partner.googleadservices.com",ma);w("securepubads.g.doubleclick.net",la);function y(a){return typeof encodeURIComponent=="function"?encodeURIComponent(a):escape(a)}function pa(a,b,c){var d=document.createElement("script");d.type="text/javascript";if(b)d.onload=b;if(c)d.id=c;d.src=a;var e=document.getElementsByTagName("head")[0];if(!e)return m;window.setTimeout(function(){e.appendChild(d)},0);return h}function qa(a,b){a.google_image_requests||(a.google_image_requests=[]);var c=new Image;c.src=b;a.google_image_requests.push(c)}
function ra(a){if(a in sa)return sa[a];return sa[a]=navigator.userAgent.toLowerCase().indexOf(a)!=-1}var sa={};
function ta(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else if(navigator.userAgent&&navigator.userAgent.indexOf("Windows CE")>=0){for(var b=3,c=1;c;)try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(b+1));b++}catch(d){c=i}return b.toString()}else if(ra("msie")&&!window.opera){c=i;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(e){b=
0;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");b=6;c.AllowScriptAccess="always"}catch(f){if(b==6)return b.toString()}try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(g){}}if(c){b=c.GetVariable("$version").split(" ")[1];return b.replace(/,/g,".")}}return"0"}function z(a){var b=a.google_ad_format;if(b)return b.indexOf("_0ads")>0;return a.google_ad_output!="html"&&a.google_num_radlinks>0}function A(a){return!!a&&a.indexOf("_sdo")!=-1}
function B(a,b){var c=Math.random();if(c<b){var d=Math.floor(c/b*a.length);return a[d]}return""}var ua=function(a){a.u_tz=-(new Date).getTimezoneOffset();a.u_his=window.history.length;a.u_java=navigator.javaEnabled();if(window.screen){a.u_h=window.screen.height;a.u_w=window.screen.width;a.u_ah=window.screen.availHeight;a.u_aw=window.screen.availWidth;a.u_cd=window.screen.colorDepth}if(navigator.plugins)a.u_nplug=navigator.plugins.length;if(navigator.mimeTypes)a.u_nmime=navigator.mimeTypes.length};var va={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",google_color_url:"color_url",
google_contents:"contents",google_country:"gl",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_font_face:"f",google_font_size:"fs",google_hints:"hints",
google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_referrer_url:"ref",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_tag_info:"gut",google_targeting:"targeting",google_ui_features:"ui",google_ui_version:"uiv",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},wa={google_ad_client:"client",google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",google_ad_height:"h",google_ad_override:"google_ad_override",
google_ad_slot:"slotname",google_ad_width:"w",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_page_location:"loc",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",google_rl_mode:"rl_mode",google_rt:"rt",google_skip:"skip"},xa=
{google_only_pyv_ads:"pyv",google_with_pyv_ads:"withpyv"};function ya(a,b){try{return a.top.document.URL==b.URL}catch(c){}return m}function za(a,b,c,d){var e=c||a.google_ad_width,f=d||a.google_ad_height;if(ya(a,b))return m;var g=b.documentElement;if(e&&f){var j=1,k=1;if(a.innerHeight){j=a.innerWidth;k=a.innerHeight}else if(g&&g.clientHeight){j=g.clientWidth;k=g.clientHeight}else if(b.body){j=b.body.clientWidth;k=b.body.clientHeight}if(k>2*f||j>2*e)return m}return h}function Aa(a,b){for(var c in b)a["google_"+c]=b[c]}
function Ba(a,b){if(!b)return a.URL;return a.referrer}function Ca(a,b){if(!b&&a.google_referrer_url==i)return"0";else if(b&&a.google_referrer_url==i)return"1";else if(!b&&a.google_referrer_url!=i)return"2";else if(b&&a.google_referrer_url!=i)return"3";return"4"}function Da(a,b,c,d){a.page_url=Ba(c,d);a.page_location=i}function Ea(a,b,c,d){a.page_url=b.google_page_url;a.page_location=Ba(c,d)||"EMPTY"}
function Fa(a,b){var c={},d=za(a,b,a.google_ad_width,a.google_ad_height);c.iframing=Ca(a,d);a.google_page_url?Ea(c,a,b,d):Da(c,a,b,d);c.last_modified_time=b.URL==c.page_url?Date.parse(b.lastModified)/1000:i;c.referrer_url=d?a.google_referrer_url:a.google_page_url&&a.google_referrer_url?a.google_referrer_url:b.referrer;return c}function Ga(a){var b={},c=a.URL.substring(a.URL.lastIndexOf("http"));b.iframing=i;b.page_url=c;b.page_location=a.URL;b.last_modified_time=i;b.referrer_url=c;return b}
function Ha(a,b){var c=Ia(a,b);Aa(a,c)}function Ia(a,b){var c;return c=a.google_page_url==i&&Ja[b.domain]?Ga(b):Fa(a,b)}var Ja={};Ja["ad.yieldmanager.com"]=h;var Ka=document,La=u("false",m),Ma=u("false",m),Na=u("false",m);u("false",m);var C=window;var Oa=function(a,b,c){var d=ga(b,n,a),e=window.onerror;window.onerror=d;try{c()}catch(f){var g=f.toString(),j="";if(f.fileName)j=f.fileName;var k=-1;if(f.lineNumber)k=f.lineNumber;var l=d(g,j,k);if(!l)throw f;}window.onerror=e};r("google_protectAndRun",Oa);
var Qa=function(a,b,c,d){if(Math.random()<0.01){var e=Ka,f=["http://",x,"/pagead/gen_204","?id=jserror","&jscb=",La?1:0,"&jscd=",Ma?1:0,"&context=",y(a),"&msg=",y(b),"&file=",y(c),"&line=",y(d.toString()),"&url=",y(e.URL.substring(0,512)),"&ref=",y(e.referrer.substring(0,512))];f.push(Pa());qa(C,f.join(""))}return!Na};r("google_handleError",Qa);
var Sa=function(a){Ra|=a},Ra=0,Pa=function(){var a=["&client=",y(C.google_ad_client),"&format=",y(C.google_ad_format),"&slotname=",y(C.google_ad_slot),"&output=",y(C.google_ad_output),"&ad_type=",y(C.google_ad_type)];return a.join("")};var E="",Va=function(){if(window.google_ad_frameborder==i)window.google_ad_frameborder=0;if(window.google_ad_output==i)window.google_ad_output="html";if(A(window.google_ad_format)){var a=window.google_ad_format.match(/^(\d+)x(\d+)_.*/);if(a){window.google_ad_width=parseInt(a[1],10);window.google_ad_height=parseInt(a[2],10);window.google_ad_output="html"}}window.google_ad_format=Ta(window.google_ad_format,window.google_ad_output,window.google_ad_width,window.google_ad_height,window.google_ad_slot,
!!window.google_override_format);E=window.google_ad_client||"";window.google_ad_client=Ua(window.google_ad_format,window.google_ad_client);Ha(window,document);if(window.google_num_slots_by_channel==i)window.google_num_slots_by_channel={};if(window.google_viewed_host_channels==i)window.google_viewed_host_channels={};if(window.google_num_slots_by_client==i)window.google_num_slots_by_client={};if(window.google_prev_ad_formats_by_region==i)window.google_prev_ad_formats_by_region={};if(window.google_prev_ad_slotnames_by_region==
i)window.google_prev_ad_slotnames_by_region={};if(window.google_correlator==i)window.google_correlator=(new Date).getTime();if(window.google_adslot_loaded==i)window.google_adslot_loaded={};if(window.google_adContentsBySlot==i)window.google_adContentsBySlot={};if(window.google_flash_version==i)window.google_flash_version=ta();if(window.google_new_domain_checked==i)window.google_new_domain_checked=0;if(window.google_new_domain_enabled==i)window.google_new_domain_enabled=0;if(!window.google_num_ad_slots)window.google_num_ad_slots=
0;if(!window.google_num_0ad_slots)window.google_num_0ad_slots=0;if(!window.google_num_sdo_slots)window.google_num_sdo_slots=0;window.google_ad_section=window.google_ad_section||window.google_ad_region||"";window.google_country=window.google_country||window.google_gl||"";var b=(new Date).getTime();if(p(window.google_color_bg))window.google_color_bg=F(window.google_color_bg,b);if(p(window.google_color_text))window.google_color_text=F(window.google_color_text,b);if(p(window.google_color_link))window.google_color_link=
F(window.google_color_link,b);if(p(window.google_color_url))window.google_color_url=F(window.google_color_url,b);if(p(window.google_color_border))window.google_color_border=F(window.google_color_border,b);if(p(window.google_color_line))window.google_color_line=F(window.google_color_line,b)},Wa=function(a){var b;for(b in va)a[b]=i;for(b in wa)a[b]=i;for(b in xa)a[b]=i;a.google_container_id=i;a.google_eids=i;a.google_ad_region=i;a.google_gl=i},F=function(a,b){Sa(2);return a[b%a.length]},Ua=function(a,
b){if(!b)return"";b=b.toLowerCase();return b=A(a)?Xa(b):Ya(b)},Ya=function(a){if(a&&a.substring(0,3)!="ca-")a="ca-"+a;return a},Xa=function(a){if(a&&a.substring(0,9)!="dist-aff-")a="dist-aff-"+a;return a},Ta=function(a,b,c,d,e,f){if(!a&&b=="html")a=c+"x"+d;return a=Za(a,e,f)?a.toLowerCase():""},Za=function(a,b,c){if(!a)return m;if(!b)return h;return c};var G=document,H=navigator,I=window;
function $a(){var a=G.cookie,b=Math.round((new Date).getTime()/1000),c=I.google_analytics_domain_name,d=typeof c=="undefined"?ab("auto"):ab(c),e=a.indexOf("__utma="+d+".")>-1,f=a.indexOf("__utmb="+d)>-1,g=a.indexOf("__utmc="+d)>-1,j,k={},l=!!I&&!!I.gaGlobal;if(e){j=a.split("__utma="+d+".")[1].split(";")[0].split(".");k.sid=f&&g?j[3]+"":l&&I.gaGlobal.sid?I.gaGlobal.sid:b+"";k.vid=j[0]+"."+j[1];k.from_cookie=h}else{k.sid=l&&I.gaGlobal.sid?I.gaGlobal.sid:b+"";k.vid=l&&I.gaGlobal.vid?I.gaGlobal.vid:(Math.round(Math.random()*
2147483647)^bb()&2147483647)+"."+b;k.from_cookie=m}k.dh=d;k.hid=l&&I.gaGlobal.hid?I.gaGlobal.hid:Math.round(Math.random()*2147483647);return I.gaGlobal=k}
function bb(){var a=G.cookie?G.cookie:"",b=I.history.length,c,d,e=[H.appName,H.version,H.language?H.language:H.browserLanguage,H.platform,H.userAgent,H.javaEnabled()?1:0].join("");if(I.screen)e+=I.screen.width+"x"+I.screen.height+I.screen.colorDepth;else if(I.java){d=java.awt.Toolkit.getDefaultToolkit().getScreenSize();e+=d.screen.width+"x"+d.screen.height}e+=a;e+=G.referrer?G.referrer:"";for(c=e.length;b>0;)e+=b--^c++;return cb(e)}
function cb(a){var b=1,c=0,d,e;if(!(a==undefined||a=="")){b=0;for(d=a.length-1;d>=0;d--){e=a.charCodeAt(d);b=(b<<6&268435455)+e+(e<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function ab(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=G.domain;if("www."==a.substring(0,4))a=a.substring(4,a.length)}return cb(a.toLowerCase())};var db={google:1,googlegroups:1,gmail:1,googlemail:1,googleimages:1,googleprint:1};function eb(a){var b=a.google_page_location||a.google_page_url;if(!b)return m;b=b.toString();if(b.indexOf("http://")==0)b=b.substring(7,b.length);else if(b.indexOf("https://")==0)b=b.substring(8,b.length);var c=b.indexOf("/");if(c==-1)c=b.length;var d=b.substring(0,c),e=d.split("."),f=m;if(e.length>=3)f=e[e.length-3]in db;if(e.length>=2)f=f||e[e.length-2]in db;return f}
function fb(a,b,c){if(eb(a)){a.google_new_domain_checked=1;return m}if(a.google_new_domain_checked==0){var d=Math.random();if(d<=c){var e="http://"+na+"/pagead/test_domain.js",f="script";b.write("<"+f+' src="'+e+'"></'+f+">");a.google_new_domain_checked=1;return h}}return m}function gb(a){if(!eb(a)&&a.google_new_domain_enabled==1)return"http://"+na;return"http://"+oa};document.URL&&(document.URL.indexOf("?google_debug")>0||document.URL.indexOf("&google_debug")>0);var hb=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},nb=function(a,b){if(b)return a.replace(ib,"&amp;").replace(jb,"&lt;").replace(kb,"&gt;").replace(lb,"&quot;");else{if(!mb.test(a))return a;if(a.indexOf("&")!=-1)a=a.replace(ib,"&amp;");if(a.indexOf("<")!=-1)a=a.replace(jb,"&lt;");if(a.indexOf(">")!=-1)a=a.replace(kb,"&gt;");if(a.indexOf('"')!=-1)a=a.replace(lb,"&quot;");return a}},ib=/&/g,jb=/</g,kb=/>/g,lb=/\"/g,mb=/[&<>\"]/,qb=function(a){if(J(a,"&"))return"document"in n&&!J(a,"<")?
ob(a):pb(a);return a},ob=function(a){var b=n.document.createElement("a");b.innerHTML=a;b.normalize&&b.normalize();a=b.firstChild.nodeValue;b.innerHTML="";return a},pb=function(a){return a.replace(/&([^;]+);/g,function(b,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if(c.charAt(0)=="#"){var d=Number("0"+c.substr(1));if(!isNaN(d))return String.fromCharCode(d)}return b}})},rb=function(a,b){for(var c=b.length,d=0;d<c;d++){var e=c==1?b:b.charAt(d);
if(a.charAt(0)==e&&a.charAt(a.length-1)==e)return a.substring(1,a.length-1)}return a},J=function(a,b){return a.indexOf(b)!=-1},tb=function(a,b){for(var c=0,d=hb(String(a)).split("."),e=hb(String(b)).split("."),f=Math.max(d.length,e.length),g=0;c==0&&g<f;g++){var j=d[g]||"",k=e[g]||"",l=new RegExp("(\\d*)(\\D*)","g"),s=new RegExp("(\\d*)(\\D*)","g");do{var D=l.exec(j)||["","",""],v=s.exec(k)||["","",""];if(D[0].length==0&&v[0].length==0)break;var ac=D[1].length==0?0:parseInt(D[1],10),bc=v[1].length==
0?0:parseInt(v[1],10);c=sb(ac,bc)||sb(D[2].length==0,v[2].length==0)||sb(D[2],v[2])}while(c==0)}return c},sb=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};ha();var K=function(a){this.u=a;this.i=[];this.p=this.h=0;this.d=[];this.n=m;this.A=""};K.prototype.s=function(a,b){var c=this.u[b],d=this.i;this.u[b]=function(e){if(e&&e.length>0){var f=e.length>1?e[1].url:i;d.push([a,qb(e[0].url),f])}c(e)}};K.prototype.r=function(){this.h++};K.prototype.o=function(){if(!this.n){pa("http://"+x+"/pagead/osd.js");this.n=h}};
K.prototype.j=function(a){if(this.h>0)for(var b=document.getElementsByTagName("iframe"),c=0;c<b.length;c++)b.item(c).name=="google_ads_frame"&&a(b.item(c),b.item(c).src)};
K.prototype.k=function(a){var b=this.i;if(b.length>0)for(var c=document.getElementsByTagName("a"),d=function(l,s){return l.innerHTML.indexOf(s)>0},e=0;e<c.length;e++)for(var f=0;f<b.length;f++)if(c.item(e).href==b[f][1]){var g=c.item(e).parentNode;if(b[f][2])for(var j=g,k=0;k<4;k++){if(d(j,b[f][2])){g=j;break}j=j.parentNode}a(g,b[f][0]);b.splice(f,1);break}};K.prototype.e=function(a){this.k(a);this.j(a)};K.prototype.b=function(a){this.p=a};K.prototype.g=function(){return this.p};
K.prototype.t=function(a){this.A=a};K.prototype.f=function(){return this.i.length+this.h};K.prototype.c=function(a){this.d=a};K.prototype.q=function(a,b){if(this.d.length>0){for(var c=0;c<this.d.length;c++)if(this.d[c]==a)if(a=="js")this.s(b,"google_ad_request_done");else a=="html"&&this.r();this.o()}};var ub=function(){window.__google_ad_urls||(window.__google_ad_urls=new K(window));return window.__google_ad_urls};r("Goog_AdSense_getAdAdapterInstance",ub);r("Goog_AdSense_OsdAdapter",K);
r("Goog_AdSense_OsdAdapter.prototype.numBlocks",K.prototype.f);r("Goog_AdSense_OsdAdapter.prototype.findBlocks",K.prototype.e);r("Goog_AdSense_OsdAdapter.prototype.getOsdMode",K.prototype.g);var vb=function(a,b,c){if(a.forEach)a.forEach(b,c);else if(Array.forEach)Array.forEach(a,b,c);else for(var d=a.length,e=q(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},wb=function(a){if(p(a))return a.concat();else{for(var b=[],c=0,d=a.length;c<d;c++)b[c]=a[c];return b}};var L=function(a,b){this.x=a!==undefined?a:0;this.y=b!==undefined?b:0};L.prototype.clone=function(){return new L(this.x,this.y)};L.prototype.toString=function(){return"("+this.x+", "+this.y+")"};var M=function(a,b){this.width=a;this.height=b};M.prototype.clone=function(){return new M(this.width,this.height)};M.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};M.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};M.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
M.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};M.prototype.scale=function(a){this.width*=a;this.height*=a;return this};var xb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};var N,yb,O,zb,Ab,Bb,Cb,Db,Eb,Fb,Gb=function(){return n.navigator?n.navigator.userAgent:i},P=function(){return n.navigator},Hb=function(){Bb=Ab=zb=O=yb=N=m;var a;if(a=Gb()){var b=P();N=a.indexOf("Opera")==0;yb=!N&&a.indexOf("MSIE")!=-1;zb=(O=!N&&a.indexOf("WebKit")!=-1)&&a.indexOf("Mobile")!=-1;Bb=(Ab=!N&&!O&&b.product=="Gecko")&&b.vendor=="Camino"}};Hb();
var Q=N,R=yb,Ib=Ab,S=O,Jb=zb,Kb=function(){var a=P();return a&&a.platform||""},Lb=Kb(),Mb=function(){Cb=J(Lb,"Mac");Db=J(Lb,"Win");Eb=J(Lb,"Linux");Fb=!!P()&&J(P().appVersion||"","X11")};Mb();
var Nb=Cb,Ob=Db,Pb=Eb,Qb=function(){var a="",b;if(Q&&n.opera){var c=n.opera.version;a=typeof c=="function"?c():c}else{if(Ib)b=/rv\:([^\);]+)(\)|;)/;else if(R)b=/MSIE\s+([^\);]+)(\)|;)/;else if(S)b=/WebKit\/(\S+)/;if(b){var d=b.exec(Gb());a=d?d[1]:""}}return a},Rb=Qb(),Sb={},T=function(a){return Sb[a]||(Sb[a]=tb(Rb,a)>=0)};var U;var Tb=function(a){return q(a)?document.getElementById(a):a},Ub=Tb,Wb=function(a,b){xb(b,function(c,d){if(d=="style")a.style.cssText=c;else if(d=="class")a.className=c;else if(d=="for")a.htmlFor=c;else if(d in Vb)a.setAttribute(Vb[d],c);else a[d]=c})},Vb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",type:"type"},Xb=function(a){var b=a.document;if(S&&!T("500")&&!Jb){if(typeof a.innerHeight==
"undefined")a=window;var c=a.innerHeight,d=a.document.documentElement.scrollHeight;if(a==a.top)if(d<c)c-=15;return new M(a.innerWidth,c)}var e=b.compatMode=="CSS1Compat"&&(!Q||Q&&T("9.50"))?b.documentElement:b.body;return new M(e.clientWidth,e.clientHeight)},Yb=function(a){var b=!S&&a.compatMode=="CSS1Compat"?a.documentElement:a.body;return new L(b.scrollLeft,b.scrollTop)},$b=function(){return Zb(document,arguments)},Zb=function(a,b){var c=b[0],d=b[1];if(R&&d&&(d.name||d.type)){var e=["<",c];d.name&&
e.push(' name="',nb(d.name),'"');if(d.type){e.push(' type="',nb(d.type),'"');d=fa(d);delete d.type}e.push(">");c=e.join("")}var f=a.createElement(c);if(d)if(q(d))f.className=d;else Wb(f,d);if(b.length>2){function g(l){if(l)f.appendChild(q(l)?a.createTextNode(l):l)}for(var j=2;j<b.length;j++){var k=b[j];da(k)&&!(ea(k)&&k.nodeType>0)?vb(cc(k)?wb(k):k,g):g(k)}}return f},dc=function(a,b){a.appendChild(b)},ec=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):i},fc=function(a,b){var c=b.parentNode;
c&&c.replaceChild(a,b)},gc=S&&T("522"),hc=function(a,b){if(typeof a.contains!="undefined"&&!gc&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a},V=function(a){return a.nodeType==9?a:a.ownerDocument||a.document},cc=function(a){if(a&&typeof a.length=="number")if(ea(a))return typeof a.item=="function"||typeof a.item=="string";else if(o(a)=="function")return typeof a.item==
"function";return m},W=function(a){this.a=a||n.document||document};W.prototype.createElement=function(a){return this.a.createElement(a)};W.prototype.createTextNode=function(a){return this.a.createTextNode(a)};W.prototype.m=function(){return this.a.compatMode=="CSS1Compat"};W.prototype.l=function(){return Yb(this.a)};W.prototype.appendChild=dc;W.prototype.removeNode=ec;W.prototype.replaceNode=fc;W.prototype.contains=hc;var ic,jc,kc,lc,mc,nc,oc=function(){nc=mc=lc=kc=jc=ic=m;var a=Gb();if(a)if(a.indexOf("Firefox")!=-1)ic=h;else if(a.indexOf("Camino")!=-1)jc=h;else if(a.indexOf("iPhone")!=-1||a.indexOf("iPod")!=-1)kc=h;else if(a.indexOf("Android")!=-1)lc=h;else if(a.indexOf("Chrome")!=-1)mc=h;else if(a.indexOf("Safari")!=-1)nc=h};oc();var pc=function(a,b){var c=V(a);if(c.defaultView&&c.defaultView.getComputedStyle){var d=c.defaultView.getComputedStyle(a,"");if(d)return d[b]}return i},X=function(a,b){return pc(a,b)||(a.currentStyle?a.currentStyle[b]:i)||a.style[b]},qc=function(a){var b;b=a?a.nodeType==9?a:V(a):document;if(R&&!(b?new W(V(b)):U||(U=new W)).m())return b.body;return b.documentElement},rc=function(a){var b=a.getBoundingClientRect();if(R){var c=a.ownerDocument;b.left-=c.documentElement.clientLeft+c.body.clientLeft;b.top-=
c.documentElement.clientTop+c.body.clientTop}return b},sc=function(a){if(R)return a.offsetParent;for(var b=V(a),c=X(a,"position"),d=c=="fixed"||c=="absolute",e=a.parentNode;e&&e!=b;e=e.parentNode){c=X(e,"position");d=d&&c=="static"&&e!=b.documentElement&&e!=b.body;if(!d&&(e.scrollWidth>e.clientWidth||e.scrollHeight>e.clientHeight||c=="fixed"||c=="absolute"))return e}return i},tc=function(a){var b,c=V(a),d=X(a,"position"),e=Ib&&c.getBoxObjectFor&&!a.getBoundingClientRect&&d=="absolute"&&(b=c.getBoxObjectFor(a))&&
(b.screenX<0||b.screenY<0),f=new L(0,0),g=qc(c);if(a==g)return f;if(a.getBoundingClientRect){b=rc(a);var j=(c?new W(V(c)):U||(U=new W)).l();f.x=b.left+j.x;f.y=b.top+j.y}else if(c.getBoxObjectFor&&!e){b=c.getBoxObjectFor(a);var k=c.getBoxObjectFor(g);f.x=b.screenX-k.screenX;f.y=b.screenY-k.screenY}else{var l=a;do{f.x+=l.offsetLeft;f.y+=l.offsetTop;if(l!=a){f.x+=l.clientLeft||0;f.y+=l.clientTop||0}if(S&&X(l,"position")=="fixed"){f.x+=c.body.scrollLeft;f.y+=c.body.scrollTop;break}l=l.offsetParent}while(l&&
l!=a);if(Q||S&&d=="absolute")f.y-=c.body.offsetTop;for(l=a;(l=sc(l))&&l!=c.body&&l!=g;){f.x-=l.scrollLeft;if(!Q||l.tagName!="TR")f.y-=l.scrollTop}}return f},uc=function(a,b,c,d){if(/^\d+px?$/.test(b))return parseInt(b,10);else{var e=a.style[c],f=a.runtimeStyle[c];a.runtimeStyle[c]=a.currentStyle[c];a.style[c]=b;var g=a.style[d];a.style[c]=e;a.runtimeStyle[c]=f;return g}},vc=function(a){var b=V(a),c="";if(b.createTextRange){var d=b.body.createTextRange();d.moveToElementText(a);c=d.queryCommandValue("FontName")}if(!c){c=
X(a,"fontFamily");if(Q&&Pb)c=c.replace(/ \[[^\]]*\]/,"")}var e=c.split(",");if(e.length>1)c=e[0];return rb(c,"\"'")},wc=/[^\d]+$/,xc=function(a){var b=a.match(wc);return b&&b[0]||i},yc={cm:1,"in":1,mm:1,pc:1,pt:1},zc={em:1,ex:1},Ac=function(a){var b=X(a,"fontSize"),c=xc(b);if(b&&"px"==c)return parseInt(b,10);if(R)if(c in yc)return uc(a,b,"left","pixelLeft");else if(a.parentNode&&a.parentNode.nodeType==1&&c in zc){var d=a.parentNode,e=X(d,"fontSize");return uc(d,b==e?"1em":b,"left","pixelLeft")}var f=
$b("span",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});dc(a,f);b=f.offsetHeight;ec(f);return b};var Y={};function Bc(a){if(a==1)return h;return!Y[a]}function Z(a,b){if(a)if(b==1)if(Y[b])Y[b]+=","+a;else Y[b]=a;else Y[b]=a}function Cc(){var a=[];for(var b in Y)a.push(Y[b]);return a.join(",")}function Dc(a,b){if(a&&a instanceof Array)for(var c=0;c<a.length;c++)a[c]&&typeof a[c]=="string"&&Z(a[c],b)}var Ec=m;
function Fc(a,b){var c="script";Ec=Gc(a,b);if(!Ec)a.google_allow_expandable_ads=m;var d=!Hc();Ec&&d&&b.write("<"+c+' src="http://'+x+'/pagead/expansion_embed.js"></'+c+">");var e=fb(a,b,t("1",0.01)),f=d||e;f&&ra("msie")&&!window.opera?b.write("<"+c+' src="http://'+x+'/pagead/render_ads.js"></'+c+">"):b.write("<"+c+'>google_protectAndRun("ads_core.google_render_ad", google_handleError, google_render_ad);</'+c+">")}function $(a){return a!=i?'"'+a+'"':'""'}
function Ic(a){var b="google_unique_id";if(a[b])++a[b];else a[b]=1;return a[b]}var Jc=function(a,b){var c=b.slice(-1),d=c=="?"||c=="#"?"":"&",e=[b];for(var f in a){var g=a[f];if(g||g===0||g===m){if(typeof g=="boolean")g=g?1:0;e.push(d,f,"=",y(g));d="&"}}return e.join("")};function Kc(){var a=R&&T("6"),b=Ib&&T("1.8.1"),c=S&&T("525");if(Ob&&(a||b||c))return h;else if(Nb&&(c||b))return h;else if(Pb&&b)return h;return m}
function Hc(){return(typeof ExpandableAdSlotFactory=="function"||typeof ExpandableAdSlotFactory=="object")&&typeof ExpandableAdSlotFactory.createIframe=="function"}function Gc(a,b){if(a.google_allow_expandable_ads===m||!b.body||a.google_ad_output!="html"||za(a,b)||!Lc(a)||isNaN(a.google_ad_height)||isNaN(a.google_ad_width)||!Kc())return m;return h}function Lc(a){var b=a.google_ad_format;if(A(b))return m;if(z(a)&&!(b=="468x15_0ads_al"))return m;return h}
function Mc(){var a;if(C.google_ad_output=="html"&&!(z(C)||A(C.google_ad_format))&&Bc(0)){var b=["6083035","6083034"];a=B(b,t("0",0));Z(a,0)}return a=="6083035"}function Nc(a,b){if((a.google_unique_id||0)==0&&a.google_ad_output=="html"&&document.body&&typeof b.body.getBoundingClientRect=="function")return B(["36812001","36812002"],t("0.01",0));return""}
function Oc(a,b){var c="";if(a.google_num_ad_slots==0){if(!(z(a)||A(a.google_ad_format)))if(b=="html")c=B(["36815001","36815002"],t("0.006",0));else if(b=="js")c=B(["36815003","36815004"],t("0.006",0));if(c==""&&(b=="html"||b=="js"))c=B(["36813005","36813006"],t("0.008",0))}return c}
function Pc(a,b){b.t(a);switch(a){case "36815004":b.b(1);b.c(["js"]);break;case "36815002":b.b(1);b.c(["html"]);break;case "36813006":b.b(0);b.c(["html","js"]);break}}function Qc(a){if(a.body)try{return Xb(window)}catch(b){return new M(-12245933,-12245933)}else return new M(-1,-1)}
function Rc(a,b,c,d){var e=Ic(a);c=Jc({ifi:e},c);c=c.substring(0,1992);c=c.replace(/%\w?$/,"");var f="script";if((a.google_ad_output=="js"||a.google_ad_output=="json_html")&&(a.google_ad_request_done||a.google_radlink_request_done))b.write("<"+f+' language="JavaScript1.1" src='+$(ba(c))+"></"+f+">");else if(a.google_ad_output=="html")if(Ec&&Hc()){var g=a.google_container_id||d||i;a["google_expandable_ad_slot"+e]=ExpandableAdSlotFactory.createIframe("google_ads_frame"+e,ba(c),a.google_ad_width,a.google_ad_height,
g)}else{var j='<iframe name="google_ads_frame" width='+$(a.google_ad_width)+" height="+$(a.google_ad_height)+" frameborder="+$(a.google_ad_frameborder)+" src="+$(ba(c))+' marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>';a.google_container_id?Sc(a.google_container_id,b,j):b.write(j)}}function Tc(a){Wa(a)}function Uc(a,b){if(!Vc())return m;var c=Mc(),d=Wc(a,b),e=gb(window)+Xc(d.google_ad_format,c);window.google_ad_url=Jc(d,e);return h}
var $c=function(a){a.dt=aa;var b=window.google_prev_ad_formats_by_region,c=window.google_ad_section,d=window.google_ad_format,e=window.google_ad_slot;if(b[c])if(!A(d)){a.prev_fmts=b[c];if(window.google_num_slots_by_client.length>1)a.slot=window.google_num_slots_by_client[E]}var f=window.google_prev_ad_slotnames_by_region;if(f[c])a.prev_slotnames=f[c].toLowerCase();if(d){if(!A(d))if(b[c])b[c]+=","+d;else b[c]=d}else if(e)if(f[c])f[c]+=","+e;else f[c]=e;a.correlator=window.google_correlator;if(window.google_new_domain_checked==
1&&window.google_new_domain_enabled==0)a.dblk=1;if(window.google_ad_channel){for(var g=window.google_num_slots_by_channel,j="",k=window.google_ad_channel.split(Yc),l=0;l<k.length;l++){var s=k[l];if(g[s])j+=s+"+";else g[s]=1}a.pv_ch=j}if(window.google_ad_host_channel){var D=Zc(window.google_ad_host_channel,window.google_viewed_host_channels);a.pv_h_ch=D}if(La)a.jscb=1;if(Ma)a.jscd=1;a.frm=window.google_iframing;var v=$a();a.ga_vid=v.vid;a.ga_sid=v.sid;a.ga_hid=v.hid;a.ga_fc=v.from_cookie;a.ga_wpids=
window.google_analytics_uacct},ad=function(a,b,c){var d;if(b)if(typeof a.getBoundingClientRect=="function"){var e=a.getBoundingClientRect();d={x:e.left,y:e.top}}else{d={};d.x="-252738";d.y="-252738"}else try{d=tc(a)}catch(f){d={};d.x="-252738";d.y="-252738"}if(d){c.adx=d.x;c.ady=d.y}},bd=function(a){var b=Qc(document);if(b){a.biw=b.width;a.bih=b.height}};
function Zc(a,b){for(var c=a.split("|"),d=-1,e=[],f=0;f<c.length;f++){var g=c[f].split(Yc);b[f]||(b[f]={});for(var j="",k=0;k<g.length;k++){var l=g[k];if(!(l==""))if(b[f][l])j+="+"+l;else b[f][l]=1}j=j.slice(1);e[f]=j;if(j!="")d=f}var s="";if(d>-1){for(f=0;f<d;f++)s+=e[f]+"|";s+=e[d]}return s}
function cd(){var a=ub(),b=window.google_enable_osd,c="";if(b===h){c="36813006";Pc(c,a)}else if(b!==m&&Bc(0)){c=B(["68120011","68120021","68120031","68120041"],t("0",0));if(c==""){c=Nc(window,document);if(c==""){c=Oc(window,window.google_ad_output);c!=""&&Pc(c,a)}}}Z(c,0);var d=m,e=m,f=m;switch(c){case "68120031":f=h;case "68120021":e=h;case "68120041":d=h;break;case "36812002":if(!window.google_atf_included){window.google_atf_included=h;pa("http://"+x+"/pagead/atf.js")}break}var g;
if(d){var j="google_temp_span";g=window.google_container_id&&Ub(window.google_container_id)||Ub(j);if(!g&&!window.google_container_id){document.write("<span id="+j+"></span>");g=Ub(j)}}var k=m;k=e?Uc(g,f):Uc();g&&g.id==j&&ec(g);if(k){a.q(window.google_ad_output,window.google_ad_url);Rc(window,document,window.google_ad_url);Tc(window)}}
var dd=function(a){var b;for(b in wa)a[wa[b]]=window[b];for(b in va)a[va[b]]=window[b];for(b in xa)a[xa[b]]=window[b]},ed=function(a){Dc(window.google_eids,1);a.eid=Cc()};function fd(a,b,c,d){var e=Qa(a,b,c,d);Fc(window,document);return e}function gd(){Va()}
function hd(a){for(var b={},c=a.split("?"),d=c[c.length-1].split("&"),e=0;e<d.length;e++){var f=d[e].split("=");if(f[0])try{b[f[0].toLowerCase()]=f.length>1?window.decodeURIComponent?decodeURIComponent(f[1].replace(/\+/g," ")):unescape(f[1]):""}catch(g){}}return b}function id(){var a=window,b=hd(document.URL);if(b.google_ad_override){a.google_ad_override=b.google_ad_override;a.google_adtest="on"}}
function Sc(a,b,c){if(a){var d=b.getElementById(a);if(d&&c&&c.length!=""){d.style.visibility="visible";d.innerHTML=c}}}
var Xc=function(a,b){var c;return c=A(a)?"/pagead/sdo?":b?"/pagead/render_iframe_ads.html#":"/pagead/ads?"},jd=function(a,b){b.dff=vc(a);b.dfs=Ac(a)},Vc=function(){var a=window.google_prev_ad_formats_by_region,b=window.google_prev_ad_slotnames_by_region,c=window.google_ad_section;if(A(window.google_ad_format)){window.google_num_sdo_slots+=1;if(window.google_num_sdo_slots>4)return m}else if(z(window)){window.google_num_0ad_slots+=1;if(window.google_num_0ad_slots>3)return m}else{window.google_num_ad_slots+=
1;if(window.google_num_slots_to_rotate){Sa(1);a[c]=i;b[c]=i;if(window.google_num_slot_to_show==i)window.google_num_slot_to_show=(new Date).getTime()%window.google_num_slots_to_rotate+1;if(window.google_num_slot_to_show!=window.google_num_ad_slots)return m}else if(window.google_num_ad_slots>6&&c=="")return m}var d=window.google_num_slots_by_client;if(d[E])d[E]+=1;else{d[E]=1;d.length+=1}return h},Wc=function(a,b){var c={};dd(c);$c(c);ua(c);if(a){jd(a,c);ad(a,!!b,c)}bd(c);ed(c);c.fu=Ra;return c},Yc=
/[+, ]/;window.google_render_ad=cd;var kd=["30143070","30143071","30143075"],ld=typeof window.postMessage=="function"||typeof window.postMessage=="object"||typeof document.postMessage=="function",nd=function(a,b){typeof A1_googleCreateSlot=="function"?A1_googleCreateSlot(a.google_ad_client):md(a,b)},pd=function(){if(!od())return m;return h},qd=function(a){if(A(a.google_ad_format))return m;var b=a.google_ad_output;if(b&&b!="html")return m;var c=a.google_ad_client;if(typeof c!="string"||c.substring(0,4)!="pub-"&&c.substring(0,7)!="ca-pub-")return m;
return h},sd=function(a){if(typeof a.google_a1_eid=="string")return a.google_a1_eid;var b=t("0.001",0);a.google_a1_eid=rd(kd,b);return a.google_a1_eid},md=function(a,b){if(!a.google_included_a1_script){var c="script",d="/pagead/show_ads_sra3.js?v\x3d1";b.write("<"+c+' src="http://'+x+d+'"></'+c+">");a.google_included_a1_script=h}},od=function(){if(R&&T("8"))return m;return ld||!S},rd=function(a,b){var c=Math.random();if(c<b){var d=Math.floor(c/b*a.length);return a[d]}return""};function td(){id();Oa("show_ads.google_init_globals",fd,gd);Fc(window,document)}function ud(){if(!pd(window)||!qd(window))td();else if(Na&&window.google_use_a1===h)nd(window,document);else{var a=sd(window);if(a){Z(a,0);window.google_allow_expandable_ads=m}!a||a=="30143070"?td():nd(window,document)}}Oa("show_ads.main",Qa,ud);
})()
