; Our SEH handlers

.386
.model flat, syscall

?Handler@ExcMon@@SA?AW4_EXCEPTION_DISPOSITION@@PAU_EXCEPTION_RECORD@@PAU1@PAU_CONTEXT@@@Z PROTO proc
?HandlerStat@MonitorRaw@Exc@@KA?AW4_EXCEPTION_DISPOSITION@@PAU_EXCEPTION_RECORD@@PAXPAU_CONTEXT@@@Z PROTO proc

.safeseh ?Handler@ExcMon@@SA?AW4_EXCEPTION_DISPOSITION@@PAU_EXCEPTION_RECORD@@PAU1@PAU_CONTEXT@@@Z
.safeseh ?HandlerStat@MonitorRaw@Exc@@KA?AW4_EXCEPTION_DISPOSITION@@PAU_EXCEPTION_RECORD@@PAXPAU_CONTEXT@@@Z

end
