(function(){var d=null,f=false,g=encodeURIComponent,i="length",j="screen",m="indexOf",n=(new Date).getTime(),o=function(a){var b=(new Date).getTime()-n;b="&dtd="+(b<1000?b:"M");return a+b};var r=this;Math.floor(Math.random()*2147483648).toString(36);var s=Date.now||function(){return(new Date).getTime()};var t=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},u=function(a,b){return a[m](b)!=-1},w=function(a,b){var c=0;a=t(String(a)).split(".");b=t(String(b)).split(".");for(var e=Math.max(a[i],b[i]),h=0;c==0&&h<e;h++){var k=a[h]||"",l=b[h]||"",M=new RegExp("(\\d*)(\\D*)","g"),N=new RegExp("(\\d*)(\\D*)","g");do{var p=M.exec(k)||["","",""],q=N.exec(l)||["","",""];if(p[0][i]==0&&q[0][i]==0)break;c=p[1][i]==0?0:parseInt(p[1],10);var O=q[1][i]==0?0:parseInt(q[1],10);c=v(c,O)||v(p[2][i]==0,q[2][i]==
0)||v(p[2],q[2])}while(c==0)}return c},v=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};s();var x,y,z,A,B,C,D,E,F,G,H=function(){return r.navigator?r.navigator.userAgent:d},I=function(){return r.navigator},J=function(){C=B=A=z=y=x=f;var a;if(a=H()){var b=I();x=a[m]("Opera")==0;y=!x&&a[m]("MSIE")!=-1;A=(z=!x&&a[m]("WebKit")!=-1)&&a[m]("Mobile")!=-1;C=(B=!x&&!z&&b.product=="Gecko")&&b.vendor=="Camino"}};J();var K=x,L=y,P=B,Q=z,R=function(){var a=I();return a&&a.platform||""},S=R(),T=function(){D=u(S,"Mac");E=u(S,"Win");F=u(S,"Linux");G=!!I()&&u(I().appVersion||"","X11")};T();
var U=function(){var a="",b;if(K&&r.opera){a=r.opera.version;a=typeof a=="function"?a():a}else{if(P)b=/rv\:([^\);]+)(\)|;)/;else if(L)b=/MSIE\s+([^\);]+)(\)|;)/;else if(Q)b=/WebKit\/(\S+)/;if(b)a=(a=b.exec(H()))?a[1]:""}return a},aa=U(),V={};Q&&(V["522"]||(V["522"]=w(aa,"522")>=0));function ba(a,b){try{return a.top.document.URL==b.URL}catch(c){}return f}function ca(a,b,c,e){c=c||a.google_ad_width;e=e||a.google_ad_height;if(ba(a,b))return f;var h=b.documentElement;if(c&&e){var k=1,l=1;if(a.innerHeight){k=a.innerWidth;l=a.innerHeight}else if(h&&h.clientHeight){k=h.clientWidth;l=h.clientHeight}else if(b.body){k=b.body.clientWidth;l=b.body.clientHeight}if(l>2*e||k>2*c)return f}return true}function W(a,b){if(!b)return a.URL;return a.referrer}
function da(a,b){if(!b&&a.google_referrer_url==d)return"0";else if(b&&a.google_referrer_url==d)return"1";else if(!b&&a.google_referrer_url!=d)return"2";else if(b&&a.google_referrer_url!=d)return"3";return"4"}function ea(a,b,c,e){a.page_url=W(c,e);a.page_location=d}function fa(a,b,c,e){a.page_url=b.google_page_url;a.page_location=W(c,e)||"EMPTY"}
function ga(a,b){var c={},e=ca(a,b,a.google_ad_width,a.google_ad_height);c.iframing=da(a,e);a.google_page_url?fa(c,a,b,e):ea(c,a,b,e);c.last_modified_time=b.URL==c.page_url?Date.parse(b.lastModified)/1000:d;c.referrer_url=e?a.google_referrer_url:a.google_page_url&&a.google_referrer_url?a.google_referrer_url:b.referrer;return c}function ha(a){var b={},c=a.URL.substring(a.URL.lastIndexOf("http"));b.iframing=d;b.page_url=c;b.page_location=a.URL;b.last_modified_time=d;b.referrer_url=c;return b}
function ia(a,b){return a=a.google_page_url==d&&X[b.domain]?ha(b):ga(a,b)}var X={};X["ad.yieldmanager.com"]=true;var Y={google_ad_channel:"channel",google_ad_format:"format",google_ad_height:"h",google_ad_width:"w",google_box_len:"box_len",google_button_pos:"btn_pos",google_color_bg:"color_bg",google_color_link:"color_link",google_color_text:"color_text",google_correlator:"correlator",google_cts_per_row:"cts_per_row",google_encoding:"oe",google_link_target:"same_win",google_logo_pos:"logo",google_rs_pos:"rl_pos",google_ss_domains:"ss_dmns",google_adtest:"adtest",google_button_color_bg:"btn_bg",google_cts_font_size:"cts_size",
google_cts_mode:"cts_mode",google_num_cts:"num_cts",google_kw:"kw",google_searchbox_color_border:"box_bdr",google_searchbox_height:"box_h",google_searchbox_width:"box_w"};function ja(a){if(a.google_ad_frameborder==d)a.google_ad_frameborder=0;if(a.google_correlator==d)a.google_correlator=n}function Z(a,b){if(a&&(b||b===0||b===f))return"&"+g(a)+"="+g(b);return""}function $(a){return a||a===0||a===f?'"'+a+'"':'""'}
function ka(a){if(a){a=a.toLowerCase();if(a.substring(0,9)!="dist-aff-")a="dist-aff-"+a}return a}
function la(a){var b="";if(a[j]){b+=Z("u_h",a[j].height);b+=Z("u_w",a[j].width);b+=Z("u_ah",a[j].availHeight);b+=Z("u_aw",a[j].availWidth);b+=Z("u_cd",a[j].colorDepth)}var c=-(new Date).getTimezoneOffset();b+=Z("u_tz",c);if(a.history)b+=Z("u_his",a.history[i]);if(a.navigator){b+=Z("u_java",a.navigator.javaEnabled());if(a.navigator.plugins)b+=Z("u_nplug",a.navigator.plugins[i]);if(a.navigator.mimeTypes)b+=Z("u_nmime",a.navigator.mimeTypes[i])}return b}
function ma(a,b){if(a.google_num_sdo_slots)if(a.google_num_sdo_slots>=4)return"";else++a.google_num_sdo_slots;else a.google_num_sdo_slots=1;var c="http://googleads.g.doubleclick.net/pagead/sdo?";c+="client="+g(ka(a.google_ad_client));c+=Z("output","html");c+=Z("dt",n);if(a.google_kw)c+=Z("kw_type","broad");for(var e in Y)c+=Z(Y[e],a[e]);c+=la(a);a=ia(a,b);c+=Z("frm",a.iframing);c+=Z("lmt",a.last_modified_time);c+=Z("url",a.page_url);c+=Z("loc",a.page_location);c+=Z("ref",a.referrer_url);return c}
function na(a){for(var b in Y)if(b!="google_correlator")a[b]=d}function oa(){var a=window,b=document;ja(a);var c=ma(a,b);c&&pa(a,b,c);na(a)}function pa(a,b,c){a='<iframe name="google_sdo_frame" width='+$(a.google_ad_width)+" height="+$(a.google_ad_height)+" frameborder="+$(a.google_ad_frameborder)+" src="+$(o(c))+' marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>';b.write(a)};oa();})()
