main: config_env.h config_posix.h main.cpp static_hash.cpp static_hash.h
	#g++ -g -o main main.cpp static_hash.cpp -lpthread
	g++ -Wno-write-strings -g -o main main.cpp static_hash.cpp -lpthread
clean:
	rm main
