// TestComObject1.idl : IDL source for TestComObject1.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (TestComObject1.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(516FAB03-BB53-4FB9-81BA-8E3191EC398D),
		dual,
		helpstring("ITestInterface1 Interface"),
		pointer_default(unique)
	]
	interface ITestInterface1 : IDispatch
	{
		[id(1), helpstring("method TestFunc1")] HRESULT TestFunc1();
	};


[
	uuid(AA727207-4883-499E-B97B-35E362D8A331),
	version(1.0),
	helpstring("TestComObject1 1.0 Type Library")
]
library TESTCOMOBJECT1Lib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(9864C676-DF91-4C1F-8E2F-3B9723CC70C4),
		helpstring("TestInterface1 Class")
	]
	coclass TestInterface1
	{
		[default] interface ITestInterface1;
	};

};
