document.write("<a title=\'GOOGLe书签\' href=\"javascript:window.open(\'http:\/\/www.google.com\/bookmarks\/mark?op=add&bkmk=\'+encodeURIComponent(location.href)+\'&title=\'+encodeURIComponent(document.title));void(0)\"><IMG src=\'\/images\/bookmark\/google.gif\' title=\'收藏到Google书签\' border=\'0\'><\/a> ");
document.write("&nbsp;&nbsp;&nbsp;<a href=\"javascript:u=location.href;t=document.title;c = %22%22 + (window.getSelection ? window.getSelection() : document.getSelection ? document.getSelection() : document.selection.createRange().text);var url=%22http:\/\/cang.baidu.com\/do\/add?it=%22+encodeURIComponent(t)+%22&amp;iu=%22+encodeURIComponent(u)+%22&amp;dc=%22+encodeURIComponent(c)+%22&amp;fr=ien#nw=1%22;window.open(url,%22_blank%22,%22scrollbars=no,width=600,height=450,left=75,top=20,status=no,resizable=yes%22); void 0\"><img title=\"收藏到百度收藏\" src=\"\/images\/bookmark\/baidu.gif\" border=\"0\"><\/a> ");
document.writeln("&nbsp;&nbsp;&nbsp;<a href=\"javascript:window.open(\'http:\/\/shuqian.qq.com\/post?from=3&title=\'+encodeURIComponent(document.title)+\'&uri=\'+encodeURIComponent(document.location.href)+\'&jumpback=2&noui=1\',\'favit\',\'width=930,height=470,left=50,top=50,toolbar=no,menubar=no,location=no,scrollbars=yes,status=yes,resizable=yes\');void(0)\"><IMG alt=QQ书签 src=\"\/images\/bookmark\/qq.gif\" border=0><\/a>");
document.write("&nbsp;&nbsp;&nbsp;<a href=\"#\" onclick=\"window.open(\'http:\/\/myweb.cn.yahoo.com\/popadd.html?url=\'+encodeURIComponent(document.location.href)+\'&title=\'+encodeURIComponent(document.title), \'Yahoo\',\'scrollbars=yes,width=780,height=455,left=80,top=80,status=yes,resizable=yes\');\"><IMG src=\"\/images\/bookmark\/yahoocn.gif\"  border=\"0\" title=\"收藏到雅虎中文书签\"><\/a> ");
document.write("&nbsp;&nbsp;&nbsp;<a href=\"javascript:d=document;t=d.selection?(d.selection.type!=\'None\'?d.selection.createRange().text:\'\'):(d.getSelection?d.getSelection():\'\');void(vivi=window.open(\'http:\/\/vivi.sina.com.cn\/collect\/icollect.php?pid=28&title=\'+escape(d.title)+\'&url=\'+escape(d.location.href)+\'&desc=\'+escape(t),\'vivi\',\'scrollbars=no,width=480,height=480,left=75,top=20,status=no,resizable=yes\'));vivi.focus();\"><IMG src=\'\/images\/bookmark\/vivi.gif\' title=\'收藏到新浪ViVi\' border=\'0\'><\/a> ");
document.write("&nbsp;&nbsp;&nbsp;<a href=\"javascript:d=document;t=d.selection?(d.selection.type!=\'None\'?d.selection.createRange().text:\'\'):(d.getSelection?d.getSelection():\'\');void(live=window.open(\'https:\/\/favorites.live.com\/quickadd.aspx?marklet=1&mkt=en-us&url=\'+escape(d.location.href)+\'&title=\'+escape(d.title)+\'&top=1\',\'live\',\'scrollbars=no,status=no,resizable=yes\'));live.focus();\"><IMG src=\"\/images\/bookmark\/live.gif\" title=\"收藏到微软Live\" border=\"0\"><\/a> ");
document.write("&nbsp;&nbsp;&nbsp;<a href=\"http:\/\/www.mister-wong.cn\/add_url\/\" onclick=\'location.href=\"http:\/\/www.mister-wong.cn\/index.php?action=addurl&bm_url=\"+encodeURIComponent(location.href)+\"&bm_description=\"+encodeURIComponent(document.title);return false\' title=\"收藏到MisterWong\" target=\"_new\"><IMG src=\"\/images\/bookmark\/wong18.gif\" alt=\"收藏到MisterWong\" border=\"0\"><\/a> ");
document.write("&nbsp;&nbsp;&nbsp;<a href=\"javascript:t=document.title;u=location.href;e=document.selection?(document.selection.type!=\'None\'?document.selection.createRange().text:\'\'):(document.getSelection?document.getSelection():\'\');void(open(\'http:\/\/bookmark.hexun.com\/post.aspx?title=\'+escape(t)+\'&url=\'+escape(u)+\'&excerpt=\'+escape(e),\'HexunBookmark\',\'scrollbars=no,width=600,height=450,left=80,top=80,status=no,resizable=yes\'));\"><IMG src=\"\/images\/bookmark\/hexun.gif\" title=\"收藏到和讯网摘\" border=\"0\"><\/a> ");
document.write("&nbsp;&nbsp;&nbsp;<a href=\"javascript:d=document;t=d.selection?(d.selection.type!=\'None\'?d.selection.createRange().text:\'\'):(d.getSelection?d.getSelection():\'\');void(hot=window.open(\'http:\/\/hot.tianya.cn\/Add.aspx?title=\'+escape(d.title)+\'&url=\'+escape(d.location.href)+\'&desc=\'+escape(t),\'hot\',\'scrollbars=no,width=410,height=517,left=75,top=20,status=no,resizable=yes\'));hot.focus();\" title=\'收藏的网页将被永久地保存\'><IMG src=\'\/images\/bookmark\/yeeyoo.gif\' title=\'收藏到天涯网藏\' border=\'0\'><\/a> ");
document.write("&nbsp;&nbsp;&nbsp;<a href=\"javascript:d=document;t=d.selection?(d.selection.type!=\'None\'?d.selection.createRange().text:\'\'):(d.getSelection?d.getSelection():\'\');void(yesky=window.open(\'http:\/\/hot.yesky.com\/dp.aspx?t=\'+escape(d.title)+\'&u=\'+escape(d.location.href)+\'&c=\'+escape(t)+\'&st=2\',\'yesky\',\'scrollbars=no,width=400,height=480,left=75,top=20,status=no,resizable=yes\'));yesky.focus();\"><IMG src=\'\/images\/bookmark\/yesky.gif\' title=\'收藏到天极网摘\' border=\'0\'><\/a> ");
document.write("&nbsp;&nbsp;&nbsp;<a href=\"javascript:d=document;t=d.selection?(d.selection.type!=\'None\'?d.selection.createRange().text:\'\'):(d.getSelection?d.getSelection():\'\');void(keyit=window.open(\'http:\/\/my.poco.cn\/fav\/storeIt.php?t=\'+escape(d.title)+\'&u=\'+escape(d.location.href)+\'&c=\'+escape(t)+\'&img=http:\/\/www.h-strong.com\/blog\/logo.gif\',\'keyit\',\'scrollbars=no,width=475,height=575,status=no,resizable=yes\'));keyit.focus();\"><IMG src=\'\/images\/bookmark\/poco.gif\' title=\'收藏到POCO网摘\' border=\'0\'><\/a> ");
document.write("&nbsp;&nbsp;&nbsp;<a href=\"javascript:d=document;t=d.selection?(d.selection.type!=\'None\'?d.selection.createRange().text:\'\'):(d.getSelection?d.getSelection():\'\');void(zhai=window.open(\'http:\/\/www.chunw.com\/sc\/#t=\'+escape(d.title)+\'&u=\'+escape(d.location.href)+\'&c=\'+escape(t),\'zhai\',\'scrollbars=no,width=400,height=410,left=75,top=50,status=no,resizable=yes\'));zhai.focus();\"><IMG src=\"\/images\/bookmark\/chunw.gif\" title=\"收藏此页到纯我网\" border=\"0\"><\/a> ");

document.write("&nbsp;&nbsp;&nbsp;<a href=javascript:window.external.AddFavorite(location.href+'#sc','★'+document.title)><IMG  src=/images/bookmark/ie.gif align=absMiddle border=0></a>");