//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SFTP.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_SFTPTYPE                    129
#define IDD_SETUPADDR                   130
#define IDD_MESSAGE                     132
#define IDB_IMAGES                      133
#define IDB_SMALLIMAGES                 134
#define IDC_SVRADDRESS                  1000
#define IDC_PORT                        1001
#define IDC_USER                        1002
#define IDC_PASS                        1003
#define IDC_PROXY                       1004
#define IDC_USERNAME                    1005
#define IDC_USERPASS                    1006
#define IDC_PROXYTYPE                   1007
#define IDC_PROXYPORT                   1008
#define IDC_TEXTOUT                     1008
#define IDC_FILE_CONNECT                32771
#define IDC_FILE_DISCONNECT             32772
#define IDC_LOGIN                       32775
#define IDS_FTPMSG1                     61446
#define IDS_FTPMSG6                     61447
#define IDS_FTPMSG5                     61448
#define IDS_COLUMN1                     61449
#define IDS_COLUMN2                     61450
#define IDS_COLUMN3                     61451
#define IDS_FTPMSG4                     61452

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1009
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
