//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by testcpl.rc
//
#define IDR_APPLET1                     131
#define IDR_APPLET2                     132
#define IDR_APPLET2_PAGE1               132
#define IDS_APPLET2_DESCRIPTION         133
#define IDR_APPLET2_PAGE2               133

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
