#ifndef __hellowdmioctl__h_
#define __hellowdmioctl__h_

#define HELLOWDM_IOCTL_HELLO	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED , FILE_ANY_ACCESS)
#define IOCTL_CREATE_DOS_NAME		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED , FILE_ANY_ACCESS)
#define IOCTL_DEL_DOS_NAME		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED , FILE_ANY_ACCESS)
#define IOCTL_GET_CURRENT_INSTANCE	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED , FILE_ANY_ACCESS)
#define IOCTL_SET_REMOTE_INSTANCE	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x805, METHOD_BUFFERED , FILE_ANY_ACCESS)
#define IOCTL_GET_REMOTE_INSTANCE	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x806, METHOD_BUFFERED , FILE_ANY_ACCESS)
#define IOCTL_DISCONNECT			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x807, METHOD_BUFFERED , FILE_ANY_ACCESS)
#define IOCTL_GET_IDENTITIER		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x808, METHOD_BUFFERED , FILE_ANY_ACCESS)
#define IOCTL_GET_CURRENT_COMX		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x809, METHOD_BUFFERED , FILE_ANY_ACCESS)


//
// Define an Interface Guid for toaster device class.
// This GUID is used to register (IoRegisterDeviceInterface) 
// an instance of an interface so that user application 
// can control the toaster device.
//

DEFINE_GUID (GUID_WDMSAMPLE_DEVICE_INTERFACE_CLASS, \
        0x781EF630, 0x72B2, 0x11d2, 0xB8, 0x52, 0x00, 0xC0, 0x4F, 0xAD, 0x51, 0x71);
//{781EF630-72B2-11d2-B852-00C04FAD5171}
#define VIRTUAL_SERIAL_DEVICE_ID 0x11223344
#endif
