//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ChatSrvr.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define ID_MESSAGES                     129
#define IDD_DISCUSSION                  130
#define ID_CONNECTIONS                  130
#define IDS_MESSAGESFMT                 131
#define IDS_CONNECTIONSFMT              132
#define IDD_CLEANSB                     135
#define IDM_CONTEXTMAIN                 136
#define IDC_EDIT1                       1000
#define IDC_CLEANLIST                   1001
#define IDC_CHECK_CONNS                 32773
#define ID_CLEAN                        32774
#define ID_ABOUT                        32776
#define ID_RESTORE                      32777
#define ID_KICKOUT                      32778
#define IDS_SERVERSHUTDOWN              61204
#define IDS_READERROR                   61205
#define IDS_SENDERROR                   61206
#define IDS_TALK0                       61207
#define IDS_TALK1                       61208
#define IDS_TALK2                       61209
#define IDS_TALK3                       61210
#define IDS_TALK4                       61211
#define IDS_TALK5                       61212
#define IDS_TALK6                       61213
#define IDS_TALK7                       61214
#define IDS_TALK8                       61215
#define IDS_TALK9                       61216
#define IDS_TALK10                      61217
#define IDS_TALK11                      61218
#define IDS_TALK12                      61219
#define IDS_TALK13                      61220
#define IDS_TALK14                      61221
#define IDS_TALK15                      61222
#define IDS_TALK16                      61223
#define IDS_TALK17                      61224
#define IDS_TALK18                      61225
#define IDS_TALK19                      61226
#define IDS_TALK20                      61227
#define IDS_TALK21                      61228
#define IDS_TALK22                      61229
#define IDS_TALK23                      61230
#define IDS_TALK24                      61231
#define IDS_TALK25                      61232
#define IDS_TALK26                      61233
#define IDS_TALK27                      61234
#define IDS_TALK28                      61235
#define IDS_TALK29                      61236
#define IDS_TALK30                      61237
#define IDS_TALK31                      61238
#define IDS_TALK32                      61239
#define ID_SYSTRAY                      61240

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
